/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface ContactMutate {
  fullname?: string;
  email?: string;
  phone?: string;
  title?: string;
  content?: string;
  status?: string;
}
