/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { DeleteContactId200AllOf } from './deleteContactId200AllOf';

export type DeleteContactId200 = ApiResponse & DeleteContactId200AllOf;
