/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { FileMutateCompressInfo } from './fileMutateCompressInfo';
import type { FileMutateImportInfo } from './fileMutateImportInfo';

export interface FileMutate {
  path?: string;
  original?: string;
  mime?: string;
  compress_info?: FileMutateCompressInfo;
  compress_status?: string;
  status?: string;
  import_info?: FileMutateImportInfo;
}
