/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10EventAddressId200AllOf } from './getApiV10EventAddressId200AllOf';

export type GetApiV10EventAddressId200 = ApiResponse & GetApiV10EventAddressId200AllOf;
