/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV10PostIdHistory200AllOfResponseDataItemAction = typeof GetApiV10PostIdHistory200AllOfResponseDataItemAction[keyof typeof GetApiV10PostIdHistory200AllOfResponseDataItemAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV10PostIdHistory200AllOfResponseDataItemAction = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const;
