/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10AdvertisementPublicType } from './getApiV10AdvertisementPublicType';

export type GetApiV10AdvertisementPublicParams = {
/**
 * Advertisement type (square or horizontal). If omitted, returns all active.
 */
type?: GetApiV10AdvertisementPublicType;
/**
 * Max number of records to return (default 20)
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
