/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type GetAdvertisementPublicType = typeof GetAdvertisementPublicType[keyof typeof GetAdvertisementPublicType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdvertisementPublicType = {
  square: 'square',
  horizontal: 'horizontal',
} as const;
