/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetAdvertisementPublic200AllOf } from './getAdvertisementPublic200AllOf';

export type GetAdvertisementPublic200 = ApiResponse & GetAdvertisementPublic200AllOf;
