/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type GetAuthProfile200DataRole = typeof GetAuthProfile200DataRole[keyof typeof GetAuthProfile200DataRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAuthProfile200DataRole = {
  user: 'user',
  admin: 'admin',
  system_admin: 'system_admin',
} as const;
