/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from './post';

export type GetPostId200AllOf = {
  responseData?: Post;
};
