/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type GetPostIdHistory200AllOfResponseDataItemActor = {
  id?: string;
  email?: string;
  /** @nullable */
  username?: string | null;
  full_name?: string;
  /** @nullable */
  avatar_url?: string | null;
};
