/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type GetPasswordResetRequestStatus = typeof GetPasswordResetRequestStatus[keyof typeof GetPasswordResetRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPasswordResetRequestStatus = {
  PENDING: 'PENDING',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
  all: 'all',
} as const;
