/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

/**
 * Trạng thái mới của user
 */
export type PatchUserIdStatusBodyStatus = typeof PatchUserIdStatusBodyStatus[keyof typeof PatchUserIdStatusBodyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchUserIdStatusBodyStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
