/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PermissionCreate {
  /** @maxLength 100 */
  name: string;
  /** @nullable */
  description?: string | null;
  /** @maxLength 100 */
  resource: string;
  /** @maxLength 50 */
  action: string;
}
