/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostApiV10CategoryTag200AllOf } from './postApiV10CategoryTag200AllOf';

export type PostApiV10CategoryTag200 = ApiResponse & PostApiV10CategoryTag200AllOf;
