/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostCategoryTagCategoryIdBulk200AllOf } from './postCategoryTagCategoryIdBulk200AllOf';

export type PostCategoryTagCategoryIdBulk200 = ApiResponse & PostCategoryTagCategoryIdBulk200AllOf;
