/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type PostPasswordResetRequestIdResolveBody = {
  /** Mật khẩu mới (nếu bỏ trống sẽ dùng vcci@2026) */
  newPassword?: string;
  /** Ghi chú của admin */
  resolveNote?: string;
};
