/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PostCategoryMutate {
  post_id?: string;
  category_id?: string;
  /** @nullable */
  created_by?: string | null;
}
