/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PostCategory {
  post_id: string;
  category_id: string;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
}
