/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV10AuthForgotPasswordRequestBody = {
  email: string;
  /** Ghi chú thêm từ user (tên, lý do, etc.) */
  note?: string;
};
