/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponse } from './loginResponse';
import type { PostAuthLogin200Message } from './postAuthLogin200Message';

export type PostAuthLogin200 = {
  success?: boolean;
  data?: LoginResponse;
  message?: PostAuthLogin200Message;
};
