/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV10PostTagPostIdBulk200AllOfResponseDataItem } from './postApiV10PostTagPostIdBulk200AllOfResponseDataItem';

export type PostApiV10PostTagPostIdBulk200AllOf = {
  responseData?: PostApiV10PostTagPostIdBulk200AllOfResponseDataItem[];
};
