/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export type PutApiV10UserRoleId200AllOf = {
  responseData?: UserRole;
};
