/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutApiV10UserRoleId200AllOf } from './putApiV10UserRoleId200AllOf';

export type PutApiV10UserRoleId200 = ApiResponse & PutApiV10UserRoleId200AllOf;
