/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutBannerId200AllOf } from './putBannerId200AllOf';

export type PutBannerId200 = ApiResponse & PutBannerId200AllOf;
