/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UserRoleUserSummary } from './userRoleUserSummary';

/**
 * @nullable
 */
export type UserRoleAssignedByUser = UserRoleUserSummary | null;
