/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type UserCreateGender = typeof UserCreateGender[keyof typeof UserCreateGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCreateGender = {
  male: 'male',
  female: 'female',
  other: 'other',
} as const;
