/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BusinessCreate,
  BusinessDeleteResponse,
  BusinessGetAllResponse,
  BusinessGetOneResponse,
  BusinessUpdate,
  GetApiV10BusinessParams
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single business record by its ID
 * @summary Get business by ID
 */
export type getApiV10BusinessIdResponse200 = {
  data: BusinessGetOneResponse
  status: 200
}

export type getApiV10BusinessIdResponse404 = {
  data: void
  status: 404
}
    
export type getApiV10BusinessIdResponseSuccess = (getApiV10BusinessIdResponse200) & {
  headers: Headers;
};
export type getApiV10BusinessIdResponseError = (getApiV10BusinessIdResponse404) & {
  headers: Headers;
};

export type getApiV10BusinessIdResponse = (getApiV10BusinessIdResponseSuccess | getApiV10BusinessIdResponseError)

export const getGetApiV10BusinessIdUrl = (id: string,) => {


  

  return `/api/v1.0/business/${id}`
}

export const getApiV10BusinessId = async (id: string, options?: RequestInit): Promise<getApiV10BusinessIdResponse> => {
  
  return useCustomClient<getApiV10BusinessIdResponse>(getGetApiV10BusinessIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiV10BusinessIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/business/${id}`
    ] as const;
    }

export const getGetApiV10BusinessIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/business/${id}`
    ] as const;
    }

    
export const getGetApiV10BusinessIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BusinessId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10BusinessIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10BusinessId>>> = ({ signal }) => getApiV10BusinessId(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10BusinessIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10BusinessId>>>
export type GetApiV10BusinessIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10BusinessIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BusinessId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10BusinessId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10BusinessId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BusinessIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BusinessId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10BusinessId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10BusinessId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BusinessIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BusinessId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get business by ID
 */

export function useGetApiV10BusinessIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BusinessId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10BusinessIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get business by ID
 */
export const prefetchGetApiV10BusinessIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10BusinessId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10BusinessIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10BusinessIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10BusinessId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10BusinessIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10BusinessId>>> = ({ signal }) => getApiV10BusinessId(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10BusinessIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10BusinessId>>>
export type GetApiV10BusinessIdQueryError = ErrorType<void>


export function useGetApiV10BusinessId<TData = Awaited<ReturnType<typeof getApiV10BusinessId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10BusinessId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10BusinessId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BusinessId<TData = Awaited<ReturnType<typeof getApiV10BusinessId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10BusinessId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10BusinessId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BusinessId<TData = Awaited<ReturnType<typeof getApiV10BusinessId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get business by ID
 */

export function useGetApiV10BusinessId<TData = Awaited<ReturnType<typeof getApiV10BusinessId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10BusinessIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get business by ID
 */
export const prefetchGetApiV10BusinessIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10BusinessId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BusinessId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10BusinessIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single business record by its ID
 * @summary Update business by ID
 */
export type putApiV10BusinessIdResponse200 = {
  data: BusinessGetOneResponse
  status: 200
}

export type putApiV10BusinessIdResponse400 = {
  data: void
  status: 400
}

export type putApiV10BusinessIdResponse404 = {
  data: void
  status: 404
}

export type putApiV10BusinessIdResponse409 = {
  data: void
  status: 409
}
    
export type putApiV10BusinessIdResponseSuccess = (putApiV10BusinessIdResponse200) & {
  headers: Headers;
};
export type putApiV10BusinessIdResponseError = (putApiV10BusinessIdResponse400 | putApiV10BusinessIdResponse404 | putApiV10BusinessIdResponse409) & {
  headers: Headers;
};

export type putApiV10BusinessIdResponse = (putApiV10BusinessIdResponseSuccess | putApiV10BusinessIdResponseError)

export const getPutApiV10BusinessIdUrl = (id: string,) => {


  

  return `/api/v1.0/business/${id}`
}

export const putApiV10BusinessId = async (id: string,
    businessUpdate: BusinessUpdate, options?: RequestInit): Promise<putApiV10BusinessIdResponse> => {
  
  return useCustomClient<putApiV10BusinessIdResponse>(getPutApiV10BusinessIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      businessUpdate,)
  }
);}




export const getPutApiV10BusinessIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10BusinessId>>, TError,{id: string;data: BodyType<BusinessUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10BusinessId>>, TError,{id: string;data: BodyType<BusinessUpdate>}, TContext> => {

const mutationKey = ['putApiV10BusinessId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10BusinessId>>, {id: string;data: BodyType<BusinessUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10BusinessId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10BusinessIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10BusinessId>>>
    export type PutApiV10BusinessIdMutationBody = BodyType<BusinessUpdate>
    export type PutApiV10BusinessIdMutationError = ErrorType<void>

    /**
 * @summary Update business by ID
 */
export const usePutApiV10BusinessId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10BusinessId>>, TError,{id: string;data: BodyType<BusinessUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10BusinessId>>,
        TError,
        {id: string;data: BodyType<BusinessUpdate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10BusinessIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single business record by its ID
 * @summary Delete business by ID
 */
export type deleteApiV10BusinessIdResponse200 = {
  data: BusinessDeleteResponse
  status: 200
}

export type deleteApiV10BusinessIdResponse404 = {
  data: void
  status: 404
}
    
export type deleteApiV10BusinessIdResponseSuccess = (deleteApiV10BusinessIdResponse200) & {
  headers: Headers;
};
export type deleteApiV10BusinessIdResponseError = (deleteApiV10BusinessIdResponse404) & {
  headers: Headers;
};

export type deleteApiV10BusinessIdResponse = (deleteApiV10BusinessIdResponseSuccess | deleteApiV10BusinessIdResponseError)

export const getDeleteApiV10BusinessIdUrl = (id: string,) => {


  

  return `/api/v1.0/business/${id}`
}

export const deleteApiV10BusinessId = async (id: string, options?: RequestInit): Promise<deleteApiV10BusinessIdResponse> => {
  
  return useCustomClient<deleteApiV10BusinessIdResponse>(getDeleteApiV10BusinessIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteApiV10BusinessIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10BusinessId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10BusinessId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10BusinessId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10BusinessId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10BusinessId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10BusinessIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10BusinessId>>>
    
    export type DeleteApiV10BusinessIdMutationError = ErrorType<void>

    /**
 * @summary Delete business by ID
 */
export const useDeleteApiV10BusinessId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10BusinessId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10BusinessId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10BusinessIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of business with pagination, filtering and sorting
 * @summary Get all business
 */
export type getApiV10BusinessResponse200 = {
  data: BusinessGetAllResponse
  status: 200
}
    
export type getApiV10BusinessResponseSuccess = (getApiV10BusinessResponse200) & {
  headers: Headers;
};
;

export type getApiV10BusinessResponse = (getApiV10BusinessResponseSuccess)

export const getGetApiV10BusinessUrl = (params?: GetApiV10BusinessParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1.0/business?${stringifiedParams}` : `/api/v1.0/business`
}

export const getApiV10Business = async (params?: GetApiV10BusinessParams, options?: RequestInit): Promise<getApiV10BusinessResponse> => {
  
  return useCustomClient<getApiV10BusinessResponse>(getGetApiV10BusinessUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiV10BusinessInfiniteQueryKey = (params?: GetApiV10BusinessParams,) => {
    return [
    'infinite', `/api/v1.0/business`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10BusinessQueryKey = (params?: GetApiV10BusinessParams,) => {
    return [
    `/api/v1.0/business`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10BusinessInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Business>>>, TError = ErrorType<unknown>>(params?: GetApiV10BusinessParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10BusinessInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Business>>> = ({ signal }) => getApiV10Business(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10BusinessInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Business>>>
export type GetApiV10BusinessInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10BusinessInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Business>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10BusinessParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Business>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Business>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BusinessInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Business>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BusinessParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Business>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Business>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BusinessInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Business>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BusinessParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all business
 */

export function useGetApiV10BusinessInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Business>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BusinessParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10BusinessInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all business
 */
export const prefetchGetApiV10BusinessInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Business>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10BusinessParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10BusinessInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10BusinessQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Business>>, TError = ErrorType<unknown>>(params?: GetApiV10BusinessParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10BusinessQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Business>>> = ({ signal }) => getApiV10Business(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10BusinessQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Business>>>
export type GetApiV10BusinessQueryError = ErrorType<unknown>


export function useGetApiV10Business<TData = Awaited<ReturnType<typeof getApiV10Business>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10BusinessParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Business>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Business>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Business<TData = Awaited<ReturnType<typeof getApiV10Business>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BusinessParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Business>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Business>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Business<TData = Awaited<ReturnType<typeof getApiV10Business>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BusinessParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all business
 */

export function useGetApiV10Business<TData = Awaited<ReturnType<typeof getApiV10Business>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BusinessParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10BusinessQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all business
 */
export const prefetchGetApiV10BusinessQuery = async <TData = Awaited<ReturnType<typeof getApiV10Business>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10BusinessParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Business>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10BusinessQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new business record
 * @summary Create a business
 */
export type postApiV10BusinessResponse200 = {
  data: BusinessGetOneResponse
  status: 200
}

export type postApiV10BusinessResponse400 = {
  data: void
  status: 400
}

export type postApiV10BusinessResponse404 = {
  data: void
  status: 404
}

export type postApiV10BusinessResponse409 = {
  data: void
  status: 409
}
    
export type postApiV10BusinessResponseSuccess = (postApiV10BusinessResponse200) & {
  headers: Headers;
};
export type postApiV10BusinessResponseError = (postApiV10BusinessResponse400 | postApiV10BusinessResponse404 | postApiV10BusinessResponse409) & {
  headers: Headers;
};

export type postApiV10BusinessResponse = (postApiV10BusinessResponseSuccess | postApiV10BusinessResponseError)

export const getPostApiV10BusinessUrl = () => {


  

  return `/api/v1.0/business`
}

export const postApiV10Business = async (businessCreate: BusinessCreate, options?: RequestInit): Promise<postApiV10BusinessResponse> => {
  
  return useCustomClient<postApiV10BusinessResponse>(getPostApiV10BusinessUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      businessCreate,)
  }
);}




export const getPostApiV10BusinessMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Business>>, TError,{data: BodyType<BusinessCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Business>>, TError,{data: BodyType<BusinessCreate>}, TContext> => {

const mutationKey = ['postApiV10Business'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Business>>, {data: BodyType<BusinessCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Business(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10BusinessMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Business>>>
    export type PostApiV10BusinessMutationBody = BodyType<BusinessCreate>
    export type PostApiV10BusinessMutationError = ErrorType<void>

    /**
 * @summary Create a business
 */
export const usePostApiV10Business = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Business>>, TError,{data: BodyType<BusinessCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Business>>,
        TError,
        {data: BodyType<BusinessCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10BusinessMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    