/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10LogoId200,
  GetApiV10LogoId200,
  GetApiV10LogoParams,
  LogoCreate,
  LogoUpdate,
  PostApiV10Logo200,
  PutApiV10LogoId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single logo record by its ID
 * @summary Get logo by ID
 */
export type getApiV10LogoIdResponse200 = {
  data: GetApiV10LogoId200
  status: 200
}

export type getApiV10LogoIdResponse404 = {
  data: void
  status: 404
}
    
export type getApiV10LogoIdResponseSuccess = (getApiV10LogoIdResponse200) & {
  headers: Headers;
};
export type getApiV10LogoIdResponseError = (getApiV10LogoIdResponse404) & {
  headers: Headers;
};

export type getApiV10LogoIdResponse = (getApiV10LogoIdResponseSuccess | getApiV10LogoIdResponseError)

export const getGetApiV10LogoIdUrl = (id: string,) => {


  

  return `/api/v1.0/logo/${id}`
}

export const getApiV10LogoId = async (id: string, options?: RequestInit): Promise<getApiV10LogoIdResponse> => {
  
  return useCustomClient<getApiV10LogoIdResponse>(getGetApiV10LogoIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiV10LogoIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/logo/${id}`
    ] as const;
    }

export const getGetApiV10LogoIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/logo/${id}`
    ] as const;
    }

    
export const getGetApiV10LogoIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LogoId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LogoIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10LogoId>>> = ({ signal }) => getApiV10LogoId(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LogoIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10LogoId>>>
export type GetApiV10LogoIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10LogoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LogoId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LogoId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LogoId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LogoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LogoId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LogoId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LogoId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LogoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LogoId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get logo by ID
 */

export function useGetApiV10LogoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LogoId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LogoIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get logo by ID
 */
export const prefetchGetApiV10LogoIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10LogoId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LogoIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10LogoIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10LogoId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LogoIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10LogoId>>> = ({ signal }) => getApiV10LogoId(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LogoIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10LogoId>>>
export type GetApiV10LogoIdQueryError = ErrorType<void>


export function useGetApiV10LogoId<TData = Awaited<ReturnType<typeof getApiV10LogoId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LogoId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LogoId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LogoId<TData = Awaited<ReturnType<typeof getApiV10LogoId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LogoId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LogoId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LogoId<TData = Awaited<ReturnType<typeof getApiV10LogoId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get logo by ID
 */

export function useGetApiV10LogoId<TData = Awaited<ReturnType<typeof getApiV10LogoId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LogoIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get logo by ID
 */
export const prefetchGetApiV10LogoIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10LogoId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LogoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LogoIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single logo record by its ID
 * @summary Update logo by ID
 */
export type putApiV10LogoIdResponse200 = {
  data: PutApiV10LogoId200
  status: 200
}

export type putApiV10LogoIdResponse400 = {
  data: void
  status: 400
}

export type putApiV10LogoIdResponse404 = {
  data: void
  status: 404
}

export type putApiV10LogoIdResponse409 = {
  data: void
  status: 409
}
    
export type putApiV10LogoIdResponseSuccess = (putApiV10LogoIdResponse200) & {
  headers: Headers;
};
export type putApiV10LogoIdResponseError = (putApiV10LogoIdResponse400 | putApiV10LogoIdResponse404 | putApiV10LogoIdResponse409) & {
  headers: Headers;
};

export type putApiV10LogoIdResponse = (putApiV10LogoIdResponseSuccess | putApiV10LogoIdResponseError)

export const getPutApiV10LogoIdUrl = (id: string,) => {


  

  return `/api/v1.0/logo/${id}`
}

export const putApiV10LogoId = async (id: string,
    logoUpdate: LogoUpdate, options?: RequestInit): Promise<putApiV10LogoIdResponse> => {
  
  return useCustomClient<putApiV10LogoIdResponse>(getPutApiV10LogoIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      logoUpdate,)
  }
);}




export const getPutApiV10LogoIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10LogoId>>, TError,{id: string;data: BodyType<LogoUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10LogoId>>, TError,{id: string;data: BodyType<LogoUpdate>}, TContext> => {

const mutationKey = ['putApiV10LogoId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10LogoId>>, {id: string;data: BodyType<LogoUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10LogoId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10LogoIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10LogoId>>>
    export type PutApiV10LogoIdMutationBody = BodyType<LogoUpdate>
    export type PutApiV10LogoIdMutationError = ErrorType<void>

    /**
 * @summary Update logo by ID
 */
export const usePutApiV10LogoId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10LogoId>>, TError,{id: string;data: BodyType<LogoUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10LogoId>>,
        TError,
        {id: string;data: BodyType<LogoUpdate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10LogoIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single logo record by its ID
 * @summary Delete logo by ID
 */
export type deleteApiV10LogoIdResponse200 = {
  data: DeleteApiV10LogoId200
  status: 200
}

export type deleteApiV10LogoIdResponse404 = {
  data: void
  status: 404
}

export type deleteApiV10LogoIdResponse409 = {
  data: void
  status: 409
}
    
export type deleteApiV10LogoIdResponseSuccess = (deleteApiV10LogoIdResponse200) & {
  headers: Headers;
};
export type deleteApiV10LogoIdResponseError = (deleteApiV10LogoIdResponse404 | deleteApiV10LogoIdResponse409) & {
  headers: Headers;
};

export type deleteApiV10LogoIdResponse = (deleteApiV10LogoIdResponseSuccess | deleteApiV10LogoIdResponseError)

export const getDeleteApiV10LogoIdUrl = (id: string,) => {


  

  return `/api/v1.0/logo/${id}`
}

export const deleteApiV10LogoId = async (id: string, options?: RequestInit): Promise<deleteApiV10LogoIdResponse> => {
  
  return useCustomClient<deleteApiV10LogoIdResponse>(getDeleteApiV10LogoIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteApiV10LogoIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10LogoId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10LogoId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10LogoId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10LogoId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10LogoId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10LogoIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10LogoId>>>
    
    export type DeleteApiV10LogoIdMutationError = ErrorType<void>

    /**
 * @summary Delete logo by ID
 */
export const useDeleteApiV10LogoId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10LogoId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10LogoId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10LogoIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of logos with pagination, filtering and sorting
 * @summary Get all logos
 */
export type getApiV10LogoResponse200 = {
  data: ResponseGetAllData
  status: 200
}
    
export type getApiV10LogoResponseSuccess = (getApiV10LogoResponse200) & {
  headers: Headers;
};
;

export type getApiV10LogoResponse = (getApiV10LogoResponseSuccess)

export const getGetApiV10LogoUrl = (params?: GetApiV10LogoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1.0/logo?${stringifiedParams}` : `/api/v1.0/logo`
}

export const getApiV10Logo = async (params?: GetApiV10LogoParams, options?: RequestInit): Promise<getApiV10LogoResponse> => {
  
  return useCustomClient<getApiV10LogoResponse>(getGetApiV10LogoUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiV10LogoInfiniteQueryKey = (params?: GetApiV10LogoParams,) => {
    return [
    'infinite', `/api/v1.0/logo`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10LogoQueryKey = (params?: GetApiV10LogoParams,) => {
    return [
    `/api/v1.0/logo`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10LogoInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Logo>>>, TError = ErrorType<unknown>>(params?: GetApiV10LogoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LogoInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Logo>>> = ({ signal }) => getApiV10Logo(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LogoInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Logo>>>
export type GetApiV10LogoInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10LogoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Logo>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10LogoParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Logo>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Logo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LogoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Logo>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LogoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Logo>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Logo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LogoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Logo>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LogoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all logos
 */

export function useGetApiV10LogoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Logo>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LogoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LogoInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all logos
 */
export const prefetchGetApiV10LogoInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Logo>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10LogoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LogoInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10LogoQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Logo>>, TError = ErrorType<unknown>>(params?: GetApiV10LogoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LogoQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Logo>>> = ({ signal }) => getApiV10Logo(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LogoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Logo>>>
export type GetApiV10LogoQueryError = ErrorType<unknown>


export function useGetApiV10Logo<TData = Awaited<ReturnType<typeof getApiV10Logo>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10LogoParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Logo>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Logo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Logo<TData = Awaited<ReturnType<typeof getApiV10Logo>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LogoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Logo>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Logo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Logo<TData = Awaited<ReturnType<typeof getApiV10Logo>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LogoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all logos
 */

export function useGetApiV10Logo<TData = Awaited<ReturnType<typeof getApiV10Logo>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LogoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LogoQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all logos
 */
export const prefetchGetApiV10LogoQuery = async <TData = Awaited<ReturnType<typeof getApiV10Logo>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10LogoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Logo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LogoQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new logo record
 * @summary Create a logo
 */
export type postApiV10LogoResponse200 = {
  data: PostApiV10Logo200
  status: 200
}

export type postApiV10LogoResponse400 = {
  data: void
  status: 400
}

export type postApiV10LogoResponse404 = {
  data: void
  status: 404
}

export type postApiV10LogoResponse409 = {
  data: void
  status: 409
}
    
export type postApiV10LogoResponseSuccess = (postApiV10LogoResponse200) & {
  headers: Headers;
};
export type postApiV10LogoResponseError = (postApiV10LogoResponse400 | postApiV10LogoResponse404 | postApiV10LogoResponse409) & {
  headers: Headers;
};

export type postApiV10LogoResponse = (postApiV10LogoResponseSuccess | postApiV10LogoResponseError)

export const getPostApiV10LogoUrl = () => {


  

  return `/api/v1.0/logo`
}

export const postApiV10Logo = async (logoCreate: LogoCreate, options?: RequestInit): Promise<postApiV10LogoResponse> => {
  
  return useCustomClient<postApiV10LogoResponse>(getPostApiV10LogoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      logoCreate,)
  }
);}




export const getPostApiV10LogoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Logo>>, TError,{data: BodyType<LogoCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Logo>>, TError,{data: BodyType<LogoCreate>}, TContext> => {

const mutationKey = ['postApiV10Logo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Logo>>, {data: BodyType<LogoCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Logo(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10LogoMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Logo>>>
    export type PostApiV10LogoMutationBody = BodyType<LogoCreate>
    export type PostApiV10LogoMutationError = ErrorType<void>

    /**
 * @summary Create a logo
 */
export const usePostApiV10Logo = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Logo>>, TError,{data: BodyType<LogoCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Logo>>,
        TError,
        {data: BodyType<LogoCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10LogoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    