/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV10SiteInformation200,
  GetApiV10SiteInformationParams,
  PutApiV10SiteInformation200,
  SiteInformationBranchMutate,
  SiteInformationSocialMutate,
  SiteInformationUpdateBody
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve current public site information configuration.
 * @summary Get current site information
 */
export type getApiV10SiteInformationResponse200 = {
  data: GetApiV10SiteInformation200
  status: 200
}
    
export type getApiV10SiteInformationResponseSuccess = (getApiV10SiteInformationResponse200) & {
  headers: Headers;
};
;

export type getApiV10SiteInformationResponse = (getApiV10SiteInformationResponseSuccess)

export const getGetApiV10SiteInformationUrl = (params?: GetApiV10SiteInformationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1.0/siteInformation?${stringifiedParams}` : `/api/v1.0/siteInformation`
}

export const getApiV10SiteInformation = async (params?: GetApiV10SiteInformationParams, options?: RequestInit): Promise<getApiV10SiteInformationResponse> => {
  
  return useCustomClient<getApiV10SiteInformationResponse>(getGetApiV10SiteInformationUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiV10SiteInformationInfiniteQueryKey = (params?: GetApiV10SiteInformationParams,) => {
    return [
    'infinite', `/api/v1.0/siteInformation`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10SiteInformationQueryKey = (params?: GetApiV10SiteInformationParams,) => {
    return [
    `/api/v1.0/siteInformation`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10SiteInformationInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformation>>>, TError = ErrorType<unknown>>(params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SiteInformationInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10SiteInformation>>> = ({ signal }) => getApiV10SiteInformation(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SiteInformationInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10SiteInformation>>>
export type GetApiV10SiteInformationInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10SiteInformationInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformation>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10SiteInformationParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformation>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformation>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformation>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformation>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current site information
 */

export function useGetApiV10SiteInformationInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformation>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SiteInformationInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get current site information
 */
export const prefetchGetApiV10SiteInformationInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SiteInformationInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10SiteInformationQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError = ErrorType<unknown>>(params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SiteInformationQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10SiteInformation>>> = ({ signal }) => getApiV10SiteInformation(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SiteInformationQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10SiteInformation>>>
export type GetApiV10SiteInformationQueryError = ErrorType<unknown>


export function useGetApiV10SiteInformation<TData = Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10SiteInformationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformation>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformation<TData = Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformation>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformation<TData = Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current site information
 */

export function useGetApiV10SiteInformation<TData = Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SiteInformationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get current site information
 */
export const prefetchGetApiV10SiteInformationQuery = async <TData = Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10SiteInformationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformation>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SiteInformationQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update current site information configuration
 * @summary Update current site information
 */
export type putApiV10SiteInformationResponse200 = {
  data: PutApiV10SiteInformation200
  status: 200
}

export type putApiV10SiteInformationResponse400 = {
  data: void
  status: 400
}

export type putApiV10SiteInformationResponse401 = {
  data: void
  status: 401
}
    
export type putApiV10SiteInformationResponseSuccess = (putApiV10SiteInformationResponse200) & {
  headers: Headers;
};
export type putApiV10SiteInformationResponseError = (putApiV10SiteInformationResponse400 | putApiV10SiteInformationResponse401) & {
  headers: Headers;
};

export type putApiV10SiteInformationResponse = (putApiV10SiteInformationResponseSuccess | putApiV10SiteInformationResponseError)

export const getPutApiV10SiteInformationUrl = () => {


  

  return `/api/v1.0/siteInformation`
}

export const putApiV10SiteInformation = async (siteInformationUpdateBody: SiteInformationUpdateBody, options?: RequestInit): Promise<putApiV10SiteInformationResponse> => {
  
  return useCustomClient<putApiV10SiteInformationResponse>(getPutApiV10SiteInformationUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      siteInformationUpdateBody,)
  }
);}




export const getPutApiV10SiteInformationMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10SiteInformation>>, TError,{data: BodyType<SiteInformationUpdateBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10SiteInformation>>, TError,{data: BodyType<SiteInformationUpdateBody>}, TContext> => {

const mutationKey = ['putApiV10SiteInformation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10SiteInformation>>, {data: BodyType<SiteInformationUpdateBody>}> = (props) => {
          const {data} = props ?? {};

          return  putApiV10SiteInformation(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10SiteInformationMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10SiteInformation>>>
    export type PutApiV10SiteInformationMutationBody = BodyType<SiteInformationUpdateBody>
    export type PutApiV10SiteInformationMutationError = ErrorType<void>

    /**
 * @summary Update current site information
 */
export const usePutApiV10SiteInformation = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10SiteInformation>>, TError,{data: BodyType<SiteInformationUpdateBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10SiteInformation>>,
        TError,
        {data: BodyType<SiteInformationUpdateBody>},
        TContext
      > => {

      const mutationOptions = getPutApiV10SiteInformationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update fixed site social link
 */
export type patchApiV10SiteInformationSocialsIdResponse200 = {
  data: void
  status: 200
}
    
export type patchApiV10SiteInformationSocialsIdResponseSuccess = (patchApiV10SiteInformationSocialsIdResponse200) & {
  headers: Headers;
};
;

export type patchApiV10SiteInformationSocialsIdResponse = (patchApiV10SiteInformationSocialsIdResponseSuccess)

export const getPatchApiV10SiteInformationSocialsIdUrl = (id: string,) => {


  

  return `/api/v1.0/siteInformation/socials/${id}`
}

export const patchApiV10SiteInformationSocialsId = async (id: string,
    siteInformationSocialMutate: SiteInformationSocialMutate, options?: RequestInit): Promise<patchApiV10SiteInformationSocialsIdResponse> => {
  
  return useCustomClient<patchApiV10SiteInformationSocialsIdResponse>(getPatchApiV10SiteInformationSocialsIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      siteInformationSocialMutate,)
  }
);}




export const getPatchApiV10SiteInformationSocialsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV10SiteInformationSocialsId>>, TError,{id: string;data: BodyType<SiteInformationSocialMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV10SiteInformationSocialsId>>, TError,{id: string;data: BodyType<SiteInformationSocialMutate>}, TContext> => {

const mutationKey = ['patchApiV10SiteInformationSocialsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV10SiteInformationSocialsId>>, {id: string;data: BodyType<SiteInformationSocialMutate>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV10SiteInformationSocialsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV10SiteInformationSocialsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV10SiteInformationSocialsId>>>
    export type PatchApiV10SiteInformationSocialsIdMutationBody = BodyType<SiteInformationSocialMutate>
    export type PatchApiV10SiteInformationSocialsIdMutationError = ErrorType<unknown>

    /**
 * @summary Update fixed site social link
 */
export const usePatchApiV10SiteInformationSocialsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV10SiteInformationSocialsId>>, TError,{id: string;data: BodyType<SiteInformationSocialMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV10SiteInformationSocialsId>>,
        TError,
        {id: string;data: BodyType<SiteInformationSocialMutate>},
        TContext
      > => {

      const mutationOptions = getPatchApiV10SiteInformationSocialsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get fixed site social links
 */
export type getApiV10SiteInformationSocialsResponse200 = {
  data: void
  status: 200
}
    
export type getApiV10SiteInformationSocialsResponseSuccess = (getApiV10SiteInformationSocialsResponse200) & {
  headers: Headers;
};
;

export type getApiV10SiteInformationSocialsResponse = (getApiV10SiteInformationSocialsResponseSuccess)

export const getGetApiV10SiteInformationSocialsUrl = () => {


  

  return `/api/v1.0/siteInformation/socials`
}

export const getApiV10SiteInformationSocials = async ( options?: RequestInit): Promise<getApiV10SiteInformationSocialsResponse> => {
  
  return useCustomClient<getApiV10SiteInformationSocialsResponse>(getGetApiV10SiteInformationSocialsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiV10SiteInformationSocialsInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1.0/siteInformation/socials`
    ] as const;
    }

export const getGetApiV10SiteInformationSocialsQueryKey = () => {
    return [
    `/api/v1.0/siteInformation/socials`
    ] as const;
    }

    
export const getGetApiV10SiteInformationSocialsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SiteInformationSocialsInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>> = ({ signal }) => getApiV10SiteInformationSocials({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SiteInformationSocialsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>>
export type GetApiV10SiteInformationSocialsInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10SiteInformationSocialsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationSocialsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationSocialsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get fixed site social links
 */

export function useGetApiV10SiteInformationSocialsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SiteInformationSocialsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get fixed site social links
 */
export const prefetchGetApiV10SiteInformationSocialsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SiteInformationSocialsInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10SiteInformationSocialsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SiteInformationSocialsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>> = ({ signal }) => getApiV10SiteInformationSocials({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SiteInformationSocialsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>>
export type GetApiV10SiteInformationSocialsQueryError = ErrorType<unknown>


export function useGetApiV10SiteInformationSocials<TData = Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationSocials<TData = Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationSocials<TData = Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get fixed site social links
 */

export function useGetApiV10SiteInformationSocials<TData = Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SiteInformationSocialsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get fixed site social links
 */
export const prefetchGetApiV10SiteInformationSocialsQuery = async <TData = Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationSocials>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SiteInformationSocialsQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update site information branch
 */
export type patchApiV10SiteInformationBranchesIdResponse200 = {
  data: void
  status: 200
}
    
export type patchApiV10SiteInformationBranchesIdResponseSuccess = (patchApiV10SiteInformationBranchesIdResponse200) & {
  headers: Headers;
};
;

export type patchApiV10SiteInformationBranchesIdResponse = (patchApiV10SiteInformationBranchesIdResponseSuccess)

export const getPatchApiV10SiteInformationBranchesIdUrl = (id: string,) => {


  

  return `/api/v1.0/siteInformation/branches/${id}`
}

export const patchApiV10SiteInformationBranchesId = async (id: string,
    siteInformationBranchMutate: SiteInformationBranchMutate, options?: RequestInit): Promise<patchApiV10SiteInformationBranchesIdResponse> => {
  
  return useCustomClient<patchApiV10SiteInformationBranchesIdResponse>(getPatchApiV10SiteInformationBranchesIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      siteInformationBranchMutate,)
  }
);}




export const getPatchApiV10SiteInformationBranchesIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV10SiteInformationBranchesId>>, TError,{id: string;data: BodyType<SiteInformationBranchMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV10SiteInformationBranchesId>>, TError,{id: string;data: BodyType<SiteInformationBranchMutate>}, TContext> => {

const mutationKey = ['patchApiV10SiteInformationBranchesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV10SiteInformationBranchesId>>, {id: string;data: BodyType<SiteInformationBranchMutate>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV10SiteInformationBranchesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV10SiteInformationBranchesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV10SiteInformationBranchesId>>>
    export type PatchApiV10SiteInformationBranchesIdMutationBody = BodyType<SiteInformationBranchMutate>
    export type PatchApiV10SiteInformationBranchesIdMutationError = ErrorType<unknown>

    /**
 * @summary Update site information branch
 */
export const usePatchApiV10SiteInformationBranchesId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV10SiteInformationBranchesId>>, TError,{id: string;data: BodyType<SiteInformationBranchMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV10SiteInformationBranchesId>>,
        TError,
        {id: string;data: BodyType<SiteInformationBranchMutate>},
        TContext
      > => {

      const mutationOptions = getPatchApiV10SiteInformationBranchesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete site information branch
 */
export type deleteApiV10SiteInformationBranchesIdResponse200 = {
  data: void
  status: 200
}
    
export type deleteApiV10SiteInformationBranchesIdResponseSuccess = (deleteApiV10SiteInformationBranchesIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiV10SiteInformationBranchesIdResponse = (deleteApiV10SiteInformationBranchesIdResponseSuccess)

export const getDeleteApiV10SiteInformationBranchesIdUrl = (id: string,) => {


  

  return `/api/v1.0/siteInformation/branches/${id}`
}

export const deleteApiV10SiteInformationBranchesId = async (id: string, options?: RequestInit): Promise<deleteApiV10SiteInformationBranchesIdResponse> => {
  
  return useCustomClient<deleteApiV10SiteInformationBranchesIdResponse>(getDeleteApiV10SiteInformationBranchesIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteApiV10SiteInformationBranchesIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10SiteInformationBranchesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10SiteInformationBranchesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10SiteInformationBranchesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10SiteInformationBranchesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10SiteInformationBranchesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10SiteInformationBranchesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10SiteInformationBranchesId>>>
    
    export type DeleteApiV10SiteInformationBranchesIdMutationError = ErrorType<unknown>

    /**
 * @summary Delete site information branch
 */
export const useDeleteApiV10SiteInformationBranchesId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10SiteInformationBranchesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10SiteInformationBranchesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10SiteInformationBranchesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get site information branches
 */
export type getApiV10SiteInformationBranchesResponse200 = {
  data: void
  status: 200
}
    
export type getApiV10SiteInformationBranchesResponseSuccess = (getApiV10SiteInformationBranchesResponse200) & {
  headers: Headers;
};
;

export type getApiV10SiteInformationBranchesResponse = (getApiV10SiteInformationBranchesResponseSuccess)

export const getGetApiV10SiteInformationBranchesUrl = () => {


  

  return `/api/v1.0/siteInformation/branches`
}

export const getApiV10SiteInformationBranches = async ( options?: RequestInit): Promise<getApiV10SiteInformationBranchesResponse> => {
  
  return useCustomClient<getApiV10SiteInformationBranchesResponse>(getGetApiV10SiteInformationBranchesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiV10SiteInformationBranchesInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1.0/siteInformation/branches`
    ] as const;
    }

export const getGetApiV10SiteInformationBranchesQueryKey = () => {
    return [
    `/api/v1.0/siteInformation/branches`
    ] as const;
    }

    
export const getGetApiV10SiteInformationBranchesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SiteInformationBranchesInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>> = ({ signal }) => getApiV10SiteInformationBranches({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SiteInformationBranchesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>>
export type GetApiV10SiteInformationBranchesInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10SiteInformationBranchesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationBranchesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationBranchesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get site information branches
 */

export function useGetApiV10SiteInformationBranchesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SiteInformationBranchesInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get site information branches
 */
export const prefetchGetApiV10SiteInformationBranchesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SiteInformationBranchesInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10SiteInformationBranchesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SiteInformationBranchesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>> = ({ signal }) => getApiV10SiteInformationBranches({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SiteInformationBranchesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>>
export type GetApiV10SiteInformationBranchesQueryError = ErrorType<unknown>


export function useGetApiV10SiteInformationBranches<TData = Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationBranches<TData = Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SiteInformationBranches<TData = Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get site information branches
 */

export function useGetApiV10SiteInformationBranches<TData = Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SiteInformationBranchesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get site information branches
 */
export const prefetchGetApiV10SiteInformationBranchesQuery = async <TData = Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SiteInformationBranches>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SiteInformationBranchesQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create site information branch
 */
export type postApiV10SiteInformationBranchesResponse200 = {
  data: void
  status: 200
}
    
export type postApiV10SiteInformationBranchesResponseSuccess = (postApiV10SiteInformationBranchesResponse200) & {
  headers: Headers;
};
;

export type postApiV10SiteInformationBranchesResponse = (postApiV10SiteInformationBranchesResponseSuccess)

export const getPostApiV10SiteInformationBranchesUrl = () => {


  

  return `/api/v1.0/siteInformation/branches`
}

export const postApiV10SiteInformationBranches = async (siteInformationBranchMutate: SiteInformationBranchMutate, options?: RequestInit): Promise<postApiV10SiteInformationBranchesResponse> => {
  
  return useCustomClient<postApiV10SiteInformationBranchesResponse>(getPostApiV10SiteInformationBranchesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      siteInformationBranchMutate,)
  }
);}




export const getPostApiV10SiteInformationBranchesMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10SiteInformationBranches>>, TError,{data: BodyType<SiteInformationBranchMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10SiteInformationBranches>>, TError,{data: BodyType<SiteInformationBranchMutate>}, TContext> => {

const mutationKey = ['postApiV10SiteInformationBranches'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10SiteInformationBranches>>, {data: BodyType<SiteInformationBranchMutate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10SiteInformationBranches(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10SiteInformationBranchesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10SiteInformationBranches>>>
    export type PostApiV10SiteInformationBranchesMutationBody = BodyType<SiteInformationBranchMutate>
    export type PostApiV10SiteInformationBranchesMutationError = ErrorType<unknown>

    /**
 * @summary Create site information branch
 */
export const usePostApiV10SiteInformationBranches = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10SiteInformationBranches>>, TError,{data: BodyType<SiteInformationBranchMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10SiteInformationBranches>>,
        TError,
        {data: BodyType<SiteInformationBranchMutate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10SiteInformationBranchesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    