/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type AdvertisementUpdateStatus = typeof AdvertisementUpdateStatus[keyof typeof AdvertisementUpdateStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdvertisementUpdateStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
