/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponseResponseData } from './apiResponseResponseData';
import type { ApiResponseViolationItem } from './apiResponseViolationItem';

export interface ApiResponse {
  message?: string;
  message_en?: string;
  responseData?: ApiResponseResponseData;
  status?: string;
  timeStamp?: string;
  violation?: ApiResponseViolationItem[];
}
