/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { BadRequestResponseError } from './badRequestResponseError';
import type { BadRequestResponseResponseData } from './badRequestResponseResponseData';
import type { BadRequestResponseViolationItem } from './badRequestResponseViolationItem';

export type BadRequestResponse = {
  success?: boolean;
  error?: BadRequestResponseError;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  message_en?: string | null;
  /** @nullable */
  responseData?: BadRequestResponseResponseData;
  status?: string;
  timeStamp?: string;
  /** @nullable */
  violation?: BadRequestResponseViolationItem[] | null;
};
