/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { BannerUpdateStatus } from './bannerUpdateStatus';

export interface BannerUpdate {
  /** @maxLength 255 */
  banner_name?: string;
  display_order?: number;
  /** @minimum 1 */
  display_time?: number;
  status?: BannerUpdateStatus;
  file_id?: string;
}
