/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetCategoryId200AllOf } from './getCategoryId200AllOf';

export type GetCategoryId200 = ApiResponse & GetCategoryId200AllOf;
