/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface LookingFor {
  email?: string;
  demand?: string;
  full_name?: string;
  organization_name?: string;
  phone?: string;
  created_at?: string;
}
