/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface MemberCreate {
  full_name: string;
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  birth_date?: string | null;
  /** @nullable */
  business_id?: string | null;
  /** @nullable */
  position_id?: string | null;
  /**
   * Chức danh tại doanh nghiệp/công ty của hội viên. Đây là trường nhập tay, không liên kết với positions.
   * @maxLength 255
   * @nullable
   */
  job_title?: string | null;
}
