/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { MigrationCheckpointMutateErrorSummary } from './migrationCheckpointMutateErrorSummary';

export interface MigrationCheckpointMutate {
  migration_name?: string;
  batch_index?: number;
  total_records?: number;
  processed_count?: number;
  failed_count?: number;
  skipped_count?: number;
  status?: string;
  error_summary?: MigrationCheckpointMutateErrorSummary;
  started_at?: string;
  completed_at?: string;
}
