/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PatchVideoId200AllOf } from './patchVideoId200AllOf';

export type PatchVideoId200 = ApiResponse & PatchVideoId200AllOf;
