/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PermissionUpdate {
  /** @maxLength 100 */
  name?: string;
  /** @nullable */
  description?: string | null;
  /** @maxLength 100 */
  resource?: string;
  /** @maxLength 50 */
  action?: string;
}
