/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PermissionCreate } from './permissionCreate';

export interface PermissionBulkCreate {
  /** @minItems 1 */
  permissions: PermissionCreate[];
}
