/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface PermisionFunction {
  id?: string;
  user_id?: string;
  read?: boolean;
  read_and_export?: boolean;
  payment?: boolean;
  admin_browse?: boolean;
  created_at?: string;
  created_by?: string;
  updated_at?: string;
  updated_by?: string;
}
