/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostHistoryMutateChanges } from './postHistoryMutateChanges';
import type { PostHistoryMutateSnapshot } from './postHistoryMutateSnapshot';

export interface PostHistoryMutate {
  post_id?: string;
  action?: string;
  actor_id?: string;
  changes?: PostHistoryMutateChanges;
  snapshot?: PostHistoryMutateSnapshot;
}
