/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ForgotPasswordVerifyOtpResponse } from './forgotPasswordVerifyOtpResponse';

export type PostApiV10AuthForgotPasswordVerifyOtp200 = {
  responseData?: ForgotPasswordVerifyOtpResponse;
};
