/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostContact200AllOf } from './postContact200AllOf';

export type PostContact200 = ApiResponse & PostContact200AllOf;
