/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostApiV10UserRole200AllOf } from './postApiV10UserRole200AllOf';

export type PostApiV10UserRole200 = ApiResponse & PostApiV10UserRole200AllOf;
