/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from './post';
import type { PostApiV10Post200AllOfResponseDataAllOf } from './postApiV10Post200AllOfResponseDataAllOf';

export type PostApiV10Post200AllOfResponseData = Post & PostApiV10Post200AllOfResponseDataAllOf;
