/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type PostEventsIdExportJoinedOrgsMode = typeof PostEventsIdExportJoinedOrgsMode[keyof typeof PostEventsIdExportJoinedOrgsMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostEventsIdExportJoinedOrgsMode = {
  excel: 'excel',
  logo: 'logo',
  all: 'all',
} as const;
