/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { MemberImportResponse } from './memberImportResponse';
import type { PostApiV10MemberImport200Violations } from './postApiV10MemberImport200Violations';

export type PostApiV10MemberImport200 = {
  message?: string;
  message_en?: string;
  responseData?: MemberImportResponse;
  status?: string;
  timeStamp?: string;
  /** @nullable */
  violations?: PostApiV10MemberImport200Violations;
};
