/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type PostOrganizationsAddMembershipFeesBodyFeesItem = {
  tax_code?: string;
  amount_paid?: number;
  invoice_number?: string;
  invoice_date?: string;
};
