/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV10PostCategoryPostIdBulk200AllOfResponseDataItem } from './postApiV10PostCategoryPostIdBulk200AllOfResponseDataItem';

export type PostApiV10PostCategoryPostIdBulk200AllOf = {
  responseData?: PostApiV10PostCategoryPostIdBulk200AllOfResponseDataItem[];
};
