/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Contact } from './contact';

export type PostContact200AllOf = {
  responseData?: Contact;
};
