/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type PostApiV10Post200AllOfResponseDataAllOfType = typeof PostApiV10Post200AllOfResponseDataAllOfType[keyof typeof PostApiV10Post200AllOfResponseDataAllOfType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiV10Post200AllOfResponseDataAllOfType = {
  buy: 'buy',
  sell: 'sell',
  partner: 'partner',
} as const;
