/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV10FileUploadBody = {
  /** File to upload */
  file?: Blob;
  /** Custom path for file storage (optional) */
  path?: string;
  /** Original filename (optional) */
  original?: string;
  /** Whether to compress the file */
  compress?: boolean;
  /** Custom extension to append to filename (optional) */
  extendName?: string;
};
