/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV10PostIdBodyAllOfStatus } from './putApiV10PostIdBodyAllOfStatus';
import type { PutApiV10PostIdBodyAllOfType } from './putApiV10PostIdBodyAllOfType';

export type PutApiV10PostIdBodyAllOf = {
  status?: PutApiV10PostIdBodyAllOfStatus;
  /** @nullable */
  type?: PutApiV10PostIdBodyAllOfType;
  category_ids?: string[];
};
