/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationDraftChanges } from './organizationDraftChanges';

export type PutOrganizationsMyOrgBody = {
  draft_changes?: OrganizationDraftChanges;
};
