/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseGetAllDataAllOfResponseData } from './responseGetAllDataAllOfResponseData';

export type ResponseGetAllDataAllOf = {
  responseData?: ResponseGetAllDataAllOfResponseData;
};
