/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface RolePermission {
  id: string;
  permission_id: string;
  /** @nullable */
  role_id?: string | null;
  /** @nullable */
  created_at?: string | null;
}
