/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface RolePermissionBulkCreateByRole {
  /**
   * Danh sách permission IDs cần gán cho role
   * @minItems 1
   */
  permission_ids: string[];
}
