/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { TermMember } from './termMember';

export interface TermPositionResponse {
  position_id: string;
  name: string;
  members: TermMember[];
}
