/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface TermPositionRequestItem {
  position_id: string;
  /** @minItems 1 */
  member_ids: string[];
}
