/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface UserClub {
  email?: string;
  name?: string;
  avatar?: string;
  club_discount?: string;
  contact_info?: string;
  org_categories?: string[];
  sort_order?: number;
}
