/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Backend Template
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface UserMeResponse {
  id?: string;
  email?: string;
  username?: string;
  /** @nullable */
  first_name?: string | null;
  /** @nullable */
  last_name?: string | null;
  status?: string;
  created_at?: string;
  updated_at?: string;
  roles?: string[];
  permissions?: string[];
}
