/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface Department {
  id?: string;
  code?: string;
  name?: string;
  note?: string;
  created_at?: string;
  created_by?: string;
  updated_at?: string;
  updated_by?: string;
}
