/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { EventOrganization } from './eventOrganization';

export type EventOrganizationBody = EventOrganization;
