/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface OrganizationCategory {
  id?: string;
  name?: string;
  name_en?: string;
  image?: string;
  seo_text?: string;
  seo_text_en?: string;
  parent_id?: string;
  group_code?: string;
  sort?: number;
}
