/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface OrganizationClub {
  id?: string;
  club_id?: string;
  org_id?: string;
  status_id?: string;
  created_at?: string;
  created_by?: string;
  updated_at?: string;
  updated_by?: string;
}
