/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface OrganizationValidation {
  status_id?: string;
  created_by?: string;
  created_at?: string;
  comment?: string;
  id?: string;
  org_id?: string;
}
