/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface Permision {
  name?: string;
  code?: string;
  group_code?: string;
  description?: string;
}
