/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PostOrganizationsExportOrgsWithInfoMode } from './postOrganizationsExportOrgsWithInfoMode';

export type PostOrganizationsExportOrgsWithInfoParams = {
club_id?: string;
mode?: PostOrganizationsExportOrgsWithInfoMode;
};
