/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VCCI
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface Status {
  id?: string;
  name?: string;
  nameEn?: string;
  code?: string;
  description?: string;
  group?: string;
  subGroup?: string;
}
