/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  ForgotPasswordResetRequest,
  ForgotPasswordSendOtpRequest,
  ForgotPasswordVerifyOtpRequest,
  GetApiV10AuthMe200,
  GetApiV10AuthProfile200,
  LoginRequest,
  PostApiV10AuthForgotPasswordRequestBody,
  PostApiV10AuthForgotPasswordVerifyOtp200,
  PostApiV10AuthLogin200,
  PostApiV10AuthLogin423,
  PostApiV10AuthLogout200,
  PostApiV10AuthRefresh200,
  PostApiV10AuthRefreshBody,
  UnauthorizedResponse,
  UserCreate
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * User quên mật khẩu gửi yêu cầu reset về admin.
Admin sẽ xem và xử lý (reset password) thay vì gửi OTP qua email.
Anti-enumeration: luôn trả 200 kể cả khi email không tồn tại.

 * @summary Forgot password - submit reset request to admin
 */
export const postApiV10AuthForgotPasswordRequest = (
    postApiV10AuthForgotPasswordRequestBody: BodyType<PostApiV10AuthForgotPasswordRequestBody>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/auth/forgot-password/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV10AuthForgotPasswordRequestBody, signal
    },
      options);
    }
  


export const getPostApiV10AuthForgotPasswordRequestMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordRequest>>, TError,{data: BodyType<PostApiV10AuthForgotPasswordRequestBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordRequest>>, TError,{data: BodyType<PostApiV10AuthForgotPasswordRequestBody>}, TContext> => {

const mutationKey = ['postApiV10AuthForgotPasswordRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordRequest>>, {data: BodyType<PostApiV10AuthForgotPasswordRequestBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10AuthForgotPasswordRequest(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10AuthForgotPasswordRequestMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordRequest>>>
    export type PostApiV10AuthForgotPasswordRequestMutationBody = BodyType<PostApiV10AuthForgotPasswordRequestBody>
    export type PostApiV10AuthForgotPasswordRequestMutationError = ErrorType<void>

    /**
 * @summary Forgot password - submit reset request to admin
 */
export const usePostApiV10AuthForgotPasswordRequest = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordRequest>>, TError,{data: BodyType<PostApiV10AuthForgotPasswordRequestBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10AuthForgotPasswordRequest>>,
        TError,
        {data: BodyType<PostApiV10AuthForgotPasswordRequestBody>},
        TContext
      > => {

      const mutationOptions = getPostApiV10AuthForgotPasswordRequestMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Reset password using reset_token
 * @summary Forgot password - confirm reset
 */
export const postApiV10AuthForgotPasswordReset = (
    forgotPasswordResetRequest: BodyType<ForgotPasswordResetRequest>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/auth/forgot-password/reset`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordResetRequest, signal
    },
      options);
    }
  


export const getPostApiV10AuthForgotPasswordResetMutationOptions = <TError = ErrorType<BadRequestResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordReset>>, TError,{data: BodyType<ForgotPasswordResetRequest>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordReset>>, TError,{data: BodyType<ForgotPasswordResetRequest>}, TContext> => {

const mutationKey = ['postApiV10AuthForgotPasswordReset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordReset>>, {data: BodyType<ForgotPasswordResetRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10AuthForgotPasswordReset(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10AuthForgotPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordReset>>>
    export type PostApiV10AuthForgotPasswordResetMutationBody = BodyType<ForgotPasswordResetRequest>
    export type PostApiV10AuthForgotPasswordResetMutationError = ErrorType<BadRequestResponse | void>

    /**
 * @summary Forgot password - confirm reset
 */
export const usePostApiV10AuthForgotPasswordReset = <TError = ErrorType<BadRequestResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordReset>>, TError,{data: BodyType<ForgotPasswordResetRequest>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10AuthForgotPasswordReset>>,
        TError,
        {data: BodyType<ForgotPasswordResetRequest>},
        TContext
      > => {

      const mutationOptions = getPostApiV10AuthForgotPasswordResetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Send OTP to email for password reset
 * @summary Forgot password - send OTP
 */
export const postApiV10AuthForgotPasswordSendOtp = (
    forgotPasswordSendOtpRequest: BodyType<ForgotPasswordSendOtpRequest>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/auth/forgot-password/send-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordSendOtpRequest, signal
    },
      options);
    }
  


export const getPostApiV10AuthForgotPasswordSendOtpMutationOptions = <TError = ErrorType<BadRequestResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordSendOtp>>, TError,{data: BodyType<ForgotPasswordSendOtpRequest>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordSendOtp>>, TError,{data: BodyType<ForgotPasswordSendOtpRequest>}, TContext> => {

const mutationKey = ['postApiV10AuthForgotPasswordSendOtp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordSendOtp>>, {data: BodyType<ForgotPasswordSendOtpRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10AuthForgotPasswordSendOtp(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10AuthForgotPasswordSendOtpMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordSendOtp>>>
    export type PostApiV10AuthForgotPasswordSendOtpMutationBody = BodyType<ForgotPasswordSendOtpRequest>
    export type PostApiV10AuthForgotPasswordSendOtpMutationError = ErrorType<BadRequestResponse | void>

    /**
 * @summary Forgot password - send OTP
 */
export const usePostApiV10AuthForgotPasswordSendOtp = <TError = ErrorType<BadRequestResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordSendOtp>>, TError,{data: BodyType<ForgotPasswordSendOtpRequest>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10AuthForgotPasswordSendOtp>>,
        TError,
        {data: BodyType<ForgotPasswordSendOtpRequest>},
        TContext
      > => {

      const mutationOptions = getPostApiV10AuthForgotPasswordSendOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Verify OTP and return reset_token
 * @summary Forgot password - verify OTP
 */
export const postApiV10AuthForgotPasswordVerifyOtp = (
    forgotPasswordVerifyOtpRequest: BodyType<ForgotPasswordVerifyOtpRequest>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10AuthForgotPasswordVerifyOtp200>(
      {url: `/api/v1.0/auth/forgot-password/verify-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordVerifyOtpRequest, signal
    },
      options);
    }
  


export const getPostApiV10AuthForgotPasswordVerifyOtpMutationOptions = <TError = ErrorType<BadRequestResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordVerifyOtp>>, TError,{data: BodyType<ForgotPasswordVerifyOtpRequest>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordVerifyOtp>>, TError,{data: BodyType<ForgotPasswordVerifyOtpRequest>}, TContext> => {

const mutationKey = ['postApiV10AuthForgotPasswordVerifyOtp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordVerifyOtp>>, {data: BodyType<ForgotPasswordVerifyOtpRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10AuthForgotPasswordVerifyOtp(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10AuthForgotPasswordVerifyOtpMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordVerifyOtp>>>
    export type PostApiV10AuthForgotPasswordVerifyOtpMutationBody = BodyType<ForgotPasswordVerifyOtpRequest>
    export type PostApiV10AuthForgotPasswordVerifyOtpMutationError = ErrorType<BadRequestResponse | void>

    /**
 * @summary Forgot password - verify OTP
 */
export const usePostApiV10AuthForgotPasswordVerifyOtp = <TError = ErrorType<BadRequestResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthForgotPasswordVerifyOtp>>, TError,{data: BodyType<ForgotPasswordVerifyOtpRequest>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10AuthForgotPasswordVerifyOtp>>,
        TError,
        {data: BodyType<ForgotPasswordVerifyOtpRequest>},
        TContext
      > => {

      const mutationOptions = getPostApiV10AuthForgotPasswordVerifyOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Authenticate user with email and password
 * @summary User login
 */
export const postApiV10AuthLogin = (
    loginRequest: BodyType<LoginRequest>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10AuthLogin200>(
      {url: `/api/v1.0/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getPostApiV10AuthLoginMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | PostApiV10AuthLogin423>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthLogin>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthLogin>>, TError,{data: BodyType<LoginRequest>}, TContext> => {

const mutationKey = ['postApiV10AuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10AuthLogin>>, {data: BodyType<LoginRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10AuthLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10AuthLogin>>>
    export type PostApiV10AuthLoginMutationBody = BodyType<LoginRequest>
    export type PostApiV10AuthLoginMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | PostApiV10AuthLogin423>

    /**
 * @summary User login
 */
export const usePostApiV10AuthLogin = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | PostApiV10AuthLogin423>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthLogin>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10AuthLogin>>,
        TError,
        {data: BodyType<LoginRequest>},
        TContext
      > => {

      const mutationOptions = getPostApiV10AuthLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Logout user and invalidate current session
 * @summary Logout user
 */
export const postApiV10AuthLogout = (
    
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10AuthLogout200>(
      {url: `/api/v1.0/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiV10AuthLogoutMutationOptions = <TError = ErrorType<UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postApiV10AuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10AuthLogout>>, void> = () => {
          

          return  postApiV10AuthLogout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10AuthLogout>>>
    
    export type PostApiV10AuthLogoutMutationError = ErrorType<UnauthorizedResponse>

    /**
 * @summary Logout user
 */
export const usePostApiV10AuthLogout = <TError = ErrorType<UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10AuthLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiV10AuthLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get current authenticated user's complete information including roles and permissions
 * @summary Get my info
 */
export const getApiV10AuthMe = (
    
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10AuthMe200>(
      {url: `/api/v1.0/auth/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10AuthMeInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1.0/auth/me`
    ] as const;
    }

export const getGetApiV10AuthMeQueryKey = () => {
    return [
    `/api/v1.0/auth/me`
    ] as const;
    }

    
export const getGetApiV10AuthMeInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthMe>>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10AuthMeInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10AuthMe>>> = ({ signal }) => getApiV10AuthMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10AuthMeInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10AuthMe>>>
export type GetApiV10AuthMeInfiniteQueryError = ErrorType<UnauthorizedResponse>


export function useGetApiV10AuthMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthMe>>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10AuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV10AuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10AuthMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthMe>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10AuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV10AuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10AuthMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthMe>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my info
 */

export function useGetApiV10AuthMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthMe>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10AuthMeInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get my info
 */
export const prefetchGetApiV10AuthMeInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10AuthMe>>, TError = ErrorType<UnauthorizedResponse>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10AuthMeInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10AuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10AuthMe>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10AuthMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10AuthMe>>> = ({ signal }) => getApiV10AuthMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10AuthMe>>>
export type GetApiV10AuthMeQueryError = ErrorType<UnauthorizedResponse>


export function useGetApiV10AuthMe<TData = Awaited<ReturnType<typeof getApiV10AuthMe>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10AuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV10AuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10AuthMe<TData = Awaited<ReturnType<typeof getApiV10AuthMe>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10AuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV10AuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10AuthMe<TData = Awaited<ReturnType<typeof getApiV10AuthMe>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my info
 */

export function useGetApiV10AuthMe<TData = Awaited<ReturnType<typeof getApiV10AuthMe>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10AuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get my info
 */
export const prefetchGetApiV10AuthMeQuery = async <TData = Awaited<ReturnType<typeof getApiV10AuthMe>>, TError = ErrorType<UnauthorizedResponse>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthMe>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10AuthMeQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Get current authenticated user's profile information
 * @summary Get user profile
 */
export const getApiV10AuthProfile = (
    
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10AuthProfile200>(
      {url: `/api/v1.0/auth/profile`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10AuthProfileInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1.0/auth/profile`
    ] as const;
    }

export const getGetApiV10AuthProfileQueryKey = () => {
    return [
    `/api/v1.0/auth/profile`
    ] as const;
    }

    
export const getGetApiV10AuthProfileInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthProfile>>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10AuthProfileInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10AuthProfile>>> = ({ signal }) => getApiV10AuthProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10AuthProfileInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10AuthProfile>>>
export type GetApiV10AuthProfileInfiniteQueryError = ErrorType<UnauthorizedResponse>


export function useGetApiV10AuthProfileInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthProfile>>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10AuthProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiV10AuthProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10AuthProfileInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthProfile>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10AuthProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiV10AuthProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10AuthProfileInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthProfile>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user profile
 */

export function useGetApiV10AuthProfileInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10AuthProfile>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10AuthProfileInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get user profile
 */
export const prefetchGetApiV10AuthProfileInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError = ErrorType<UnauthorizedResponse>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10AuthProfileInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10AuthProfileQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10AuthProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10AuthProfile>>> = ({ signal }) => getApiV10AuthProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10AuthProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10AuthProfile>>>
export type GetApiV10AuthProfileQueryError = ErrorType<UnauthorizedResponse>


export function useGetApiV10AuthProfile<TData = Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10AuthProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiV10AuthProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10AuthProfile<TData = Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10AuthProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiV10AuthProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10AuthProfile<TData = Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user profile
 */

export function useGetApiV10AuthProfile<TData = Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10AuthProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get user profile
 */
export const prefetchGetApiV10AuthProfileQuery = async <TData = Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError = ErrorType<UnauthorizedResponse>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10AuthProfile>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10AuthProfileQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Get a new access token using refresh token from cookie or body
 * @summary Refresh access token
 */
export const postApiV10AuthRefresh = (
    postApiV10AuthRefreshBody?: BodyType<PostApiV10AuthRefreshBody>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10AuthRefresh200>(
      {url: `/api/v1.0/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV10AuthRefreshBody, signal
    },
      options);
    }
  


export const getPostApiV10AuthRefreshMutationOptions = <TError = ErrorType<UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthRefresh>>, TError,{data: BodyType<PostApiV10AuthRefreshBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthRefresh>>, TError,{data: BodyType<PostApiV10AuthRefreshBody>}, TContext> => {

const mutationKey = ['postApiV10AuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10AuthRefresh>>, {data: BodyType<PostApiV10AuthRefreshBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10AuthRefresh(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10AuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10AuthRefresh>>>
    export type PostApiV10AuthRefreshMutationBody = BodyType<PostApiV10AuthRefreshBody>
    export type PostApiV10AuthRefreshMutationError = ErrorType<UnauthorizedResponse>

    /**
 * @summary Refresh access token
 */
export const usePostApiV10AuthRefresh = <TError = ErrorType<UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthRefresh>>, TError,{data: BodyType<PostApiV10AuthRefreshBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10AuthRefresh>>,
        TError,
        {data: BodyType<PostApiV10AuthRefreshBody>},
        TContext
      > => {

      const mutationOptions = getPostApiV10AuthRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Register a new account
 */
export const postApiV10AuthRegister = (
    userCreate: BodyType<UserCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCreate, signal
    },
      options);
    }
  


export const getPostApiV10AuthRegisterMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthRegister>>, TError,{data: BodyType<UserCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthRegister>>, TError,{data: BodyType<UserCreate>}, TContext> => {

const mutationKey = ['postApiV10AuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10AuthRegister>>, {data: BodyType<UserCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10AuthRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10AuthRegister>>>
    export type PostApiV10AuthRegisterMutationBody = BodyType<UserCreate>
    export type PostApiV10AuthRegisterMutationError = ErrorType<void>

    /**
 * @summary Register a new account
 */
export const usePostApiV10AuthRegister = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10AuthRegister>>, TError,{data: BodyType<UserCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10AuthRegister>>,
        TError,
        {data: BodyType<UserCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10AuthRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    