/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BannerCreate,
  DeleteApiV10BannerId200,
  GetApiV10BannerId200,
  GetApiV10BannerParams,
  PostApiV10Banner200,
  PutApiV10BannerId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single banner record by its ID
 * @summary Get banner by ID
 */
export const getApiV10BannerId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10BannerId200>(
      {url: `/api/v1.0/banner/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10BannerIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/banner/${id}`
    ] as const;
    }

export const getGetApiV10BannerIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/banner/${id}`
    ] as const;
    }

    
export const getGetApiV10BannerIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BannerId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10BannerIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10BannerId>>> = ({ signal }) => getApiV10BannerId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10BannerIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10BannerId>>>
export type GetApiV10BannerIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10BannerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BannerId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10BannerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10BannerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BannerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BannerId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10BannerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10BannerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BannerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BannerId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get banner by ID
 */

export function useGetApiV10BannerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10BannerId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10BannerIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get banner by ID
 */
export const prefetchGetApiV10BannerIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10BannerId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10BannerIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10BannerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10BannerId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10BannerIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10BannerId>>> = ({ signal }) => getApiV10BannerId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10BannerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10BannerId>>>
export type GetApiV10BannerIdQueryError = ErrorType<void>


export function useGetApiV10BannerId<TData = Awaited<ReturnType<typeof getApiV10BannerId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10BannerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10BannerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BannerId<TData = Awaited<ReturnType<typeof getApiV10BannerId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10BannerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10BannerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BannerId<TData = Awaited<ReturnType<typeof getApiV10BannerId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get banner by ID
 */

export function useGetApiV10BannerId<TData = Awaited<ReturnType<typeof getApiV10BannerId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10BannerIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get banner by ID
 */
export const prefetchGetApiV10BannerIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10BannerId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10BannerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10BannerIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single banner record by its ID
 * @summary Update banner by ID
 */
export const putApiV10BannerId = (
    id: string,
    bannerCreate: BodyType<BannerCreate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10BannerId200>(
      {url: `/api/v1.0/banner/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: bannerCreate
    },
      options);
    }
  


export const getPutApiV10BannerIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10BannerId>>, TError,{id: string;data: BodyType<BannerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10BannerId>>, TError,{id: string;data: BodyType<BannerCreate>}, TContext> => {

const mutationKey = ['putApiV10BannerId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10BannerId>>, {id: string;data: BodyType<BannerCreate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10BannerId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10BannerIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10BannerId>>>
    export type PutApiV10BannerIdMutationBody = BodyType<BannerCreate>
    export type PutApiV10BannerIdMutationError = ErrorType<void>

    /**
 * @summary Update banner by ID
 */
export const usePutApiV10BannerId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10BannerId>>, TError,{id: string;data: BodyType<BannerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10BannerId>>,
        TError,
        {id: string;data: BodyType<BannerCreate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10BannerIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single banner record by its ID
 * @summary Delete banner by ID
 */
export const deleteApiV10BannerId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10BannerId200>(
      {url: `/api/v1.0/banner/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10BannerIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10BannerId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10BannerId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10BannerId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10BannerId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10BannerId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10BannerIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10BannerId>>>
    
    export type DeleteApiV10BannerIdMutationError = ErrorType<void>

    /**
 * @summary Delete banner by ID
 */
export const useDeleteApiV10BannerId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10BannerId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10BannerId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10BannerIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of banner with pagination, filtering and sorting
 * @summary Get all banner
 */
export const getApiV10Banner = (
    params?: GetApiV10BannerParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/banner`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10BannerInfiniteQueryKey = (params?: GetApiV10BannerParams,) => {
    return [
    'infinite', `/api/v1.0/banner`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10BannerQueryKey = (params?: GetApiV10BannerParams,) => {
    return [
    `/api/v1.0/banner`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10BannerInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Banner>>>, TError = ErrorType<unknown>>(params?: GetApiV10BannerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10BannerInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Banner>>> = ({ signal }) => getApiV10Banner(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10BannerInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Banner>>>
export type GetApiV10BannerInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10BannerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Banner>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10BannerParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Banner>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Banner>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BannerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Banner>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BannerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Banner>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Banner>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10BannerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Banner>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BannerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all banner
 */

export function useGetApiV10BannerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Banner>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BannerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10BannerInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all banner
 */
export const prefetchGetApiV10BannerInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Banner>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10BannerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10BannerInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10BannerQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Banner>>, TError = ErrorType<unknown>>(params?: GetApiV10BannerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10BannerQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Banner>>> = ({ signal }) => getApiV10Banner(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10BannerQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Banner>>>
export type GetApiV10BannerQueryError = ErrorType<unknown>


export function useGetApiV10Banner<TData = Awaited<ReturnType<typeof getApiV10Banner>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10BannerParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Banner>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Banner>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Banner<TData = Awaited<ReturnType<typeof getApiV10Banner>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BannerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Banner>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Banner>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Banner<TData = Awaited<ReturnType<typeof getApiV10Banner>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BannerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all banner
 */

export function useGetApiV10Banner<TData = Awaited<ReturnType<typeof getApiV10Banner>>, TError = ErrorType<unknown>>(
 params?: GetApiV10BannerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10BannerQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all banner
 */
export const prefetchGetApiV10BannerQuery = async <TData = Awaited<ReturnType<typeof getApiV10Banner>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10BannerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Banner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10BannerQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new banner record
 * @summary Create a banner
 */
export const postApiV10Banner = (
    bannerCreate: BodyType<BannerCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10Banner200>(
      {url: `/api/v1.0/banner`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bannerCreate, signal
    },
      options);
    }
  


export const getPostApiV10BannerMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Banner>>, TError,{data: BodyType<BannerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Banner>>, TError,{data: BodyType<BannerCreate>}, TContext> => {

const mutationKey = ['postApiV10Banner'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Banner>>, {data: BodyType<BannerCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Banner(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10BannerMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Banner>>>
    export type PostApiV10BannerMutationBody = BodyType<BannerCreate>
    export type PostApiV10BannerMutationError = ErrorType<unknown>

    /**
 * @summary Create a banner
 */
export const usePostApiV10Banner = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Banner>>, TError,{data: BodyType<BannerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Banner>>,
        TError,
        {data: BodyType<BannerCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10BannerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    