/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CategoryTagMutate,
  GetApiV10CategoryTagParams,
  PostApiV10CategoryTag200,
  PostApiV10CategoryTagCategoryIdBulk200,
  PostApiV10CategoryTagCategoryIdBulkBody,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve all tags for a specific category
 * @summary Get category tags by category ID
 */
export const getApiV10CategoryTagCategoryId = (
    categoryId: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/categoryTag/${categoryId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10CategoryTagCategoryIdInfiniteQueryKey = (categoryId?: string,) => {
    return [
    'infinite', `/api/v1.0/categoryTag/${categoryId}`
    ] as const;
    }

export const getGetApiV10CategoryTagCategoryIdQueryKey = (categoryId?: string,) => {
    return [
    `/api/v1.0/categoryTag/${categoryId}`
    ] as const;
    }

    
export const getGetApiV10CategoryTagCategoryIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>>, TError = ErrorType<unknown>>(categoryId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CategoryTagCategoryIdInfiniteQueryKey(categoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>> = ({ signal }) => getApiV10CategoryTagCategoryId(categoryId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(categoryId),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CategoryTagCategoryIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>>
export type GetApiV10CategoryTagCategoryIdInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10CategoryTagCategoryIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>>, TError = ErrorType<unknown>>(
 categoryId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CategoryTagCategoryIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>>, TError = ErrorType<unknown>>(
 categoryId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CategoryTagCategoryIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>>, TError = ErrorType<unknown>>(
 categoryId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get category tags by category ID
 */

export function useGetApiV10CategoryTagCategoryIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>>, TError = ErrorType<unknown>>(
 categoryId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CategoryTagCategoryIdInfiniteQueryOptions(categoryId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get category tags by category ID
 */
export const prefetchGetApiV10CategoryTagCategoryIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, categoryId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CategoryTagCategoryIdInfiniteQueryOptions(categoryId,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10CategoryTagCategoryIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError = ErrorType<unknown>>(categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CategoryTagCategoryIdQueryKey(categoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>> = ({ signal }) => getApiV10CategoryTagCategoryId(categoryId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(categoryId),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CategoryTagCategoryIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>>
export type GetApiV10CategoryTagCategoryIdQueryError = ErrorType<unknown>


export function useGetApiV10CategoryTagCategoryId<TData = Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError = ErrorType<unknown>>(
 categoryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CategoryTagCategoryId<TData = Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError = ErrorType<unknown>>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CategoryTagCategoryId<TData = Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError = ErrorType<unknown>>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get category tags by category ID
 */

export function useGetApiV10CategoryTagCategoryId<TData = Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError = ErrorType<unknown>>(
 categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CategoryTagCategoryIdQueryOptions(categoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get category tags by category ID
 */
export const prefetchGetApiV10CategoryTagCategoryIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, categoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTagCategoryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CategoryTagCategoryIdQueryOptions(categoryId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create multiple category-tag associations for a single category
 * @summary Bulk create category tags
 */
export const postApiV10CategoryTagCategoryIdBulk = (
    categoryId: string,
    postApiV10CategoryTagCategoryIdBulkBody: BodyType<PostApiV10CategoryTagCategoryIdBulkBody>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10CategoryTagCategoryIdBulk200>(
      {url: `/api/v1.0/categoryTag/${categoryId}/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV10CategoryTagCategoryIdBulkBody, signal
    },
      options);
    }
  


export const getPostApiV10CategoryTagCategoryIdBulkMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10CategoryTagCategoryIdBulk>>, TError,{categoryId: string;data: BodyType<PostApiV10CategoryTagCategoryIdBulkBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10CategoryTagCategoryIdBulk>>, TError,{categoryId: string;data: BodyType<PostApiV10CategoryTagCategoryIdBulkBody>}, TContext> => {

const mutationKey = ['postApiV10CategoryTagCategoryIdBulk'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10CategoryTagCategoryIdBulk>>, {categoryId: string;data: BodyType<PostApiV10CategoryTagCategoryIdBulkBody>}> = (props) => {
          const {categoryId,data} = props ?? {};

          return  postApiV10CategoryTagCategoryIdBulk(categoryId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10CategoryTagCategoryIdBulkMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10CategoryTagCategoryIdBulk>>>
    export type PostApiV10CategoryTagCategoryIdBulkMutationBody = BodyType<PostApiV10CategoryTagCategoryIdBulkBody>
    export type PostApiV10CategoryTagCategoryIdBulkMutationError = ErrorType<unknown>

    /**
 * @summary Bulk create category tags
 */
export const usePostApiV10CategoryTagCategoryIdBulk = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10CategoryTagCategoryIdBulk>>, TError,{categoryId: string;data: BodyType<PostApiV10CategoryTagCategoryIdBulkBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10CategoryTagCategoryIdBulk>>,
        TError,
        {categoryId: string;data: BodyType<PostApiV10CategoryTagCategoryIdBulkBody>},
        TContext
      > => {

      const mutationOptions = getPostApiV10CategoryTagCategoryIdBulkMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a specific category-tag association
 * @summary Delete a category tag
 */
export const deleteApiV10CategoryTagCategoryIdTagId = (
    categoryId: string,
    tagId: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/categoryTag/${categoryId}/${tagId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10CategoryTagCategoryIdTagIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10CategoryTagCategoryIdTagId>>, TError,{categoryId: string;tagId: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10CategoryTagCategoryIdTagId>>, TError,{categoryId: string;tagId: string}, TContext> => {

const mutationKey = ['deleteApiV10CategoryTagCategoryIdTagId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10CategoryTagCategoryIdTagId>>, {categoryId: string;tagId: string}> = (props) => {
          const {categoryId,tagId} = props ?? {};

          return  deleteApiV10CategoryTagCategoryIdTagId(categoryId,tagId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10CategoryTagCategoryIdTagIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10CategoryTagCategoryIdTagId>>>
    
    export type DeleteApiV10CategoryTagCategoryIdTagIdMutationError = ErrorType<unknown>

    /**
 * @summary Delete a category tag
 */
export const useDeleteApiV10CategoryTagCategoryIdTagId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10CategoryTagCategoryIdTagId>>, TError,{categoryId: string;tagId: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10CategoryTagCategoryIdTagId>>,
        TError,
        {categoryId: string;tagId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10CategoryTagCategoryIdTagIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of category tags with pagination, filtering and sorting
 * @summary Get all category tags
 */
export const getApiV10CategoryTag = (
    params?: GetApiV10CategoryTagParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/categoryTag`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10CategoryTagInfiniteQueryKey = (params?: GetApiV10CategoryTagParams,) => {
    return [
    'infinite', `/api/v1.0/categoryTag`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10CategoryTagQueryKey = (params?: GetApiV10CategoryTagParams,) => {
    return [
    `/api/v1.0/categoryTag`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10CategoryTagInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTag>>>, TError = ErrorType<unknown>>(params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CategoryTagInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CategoryTag>>> = ({ signal }) => getApiV10CategoryTag(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CategoryTagInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CategoryTag>>>
export type GetApiV10CategoryTagInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10CategoryTagInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTag>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10CategoryTagParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CategoryTag>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CategoryTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CategoryTagInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTag>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CategoryTag>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CategoryTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CategoryTagInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTag>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all category tags
 */

export function useGetApiV10CategoryTagInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CategoryTag>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CategoryTagInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all category tags
 */
export const prefetchGetApiV10CategoryTagInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CategoryTagInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10CategoryTagQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError = ErrorType<unknown>>(params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CategoryTagQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CategoryTag>>> = ({ signal }) => getApiV10CategoryTag(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CategoryTagQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CategoryTag>>>
export type GetApiV10CategoryTagQueryError = ErrorType<unknown>


export function useGetApiV10CategoryTag<TData = Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10CategoryTagParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CategoryTag>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CategoryTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CategoryTag<TData = Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CategoryTag>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CategoryTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CategoryTag<TData = Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all category tags
 */

export function useGetApiV10CategoryTag<TData = Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CategoryTagQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all category tags
 */
export const prefetchGetApiV10CategoryTagQuery = async <TData = Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10CategoryTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CategoryTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CategoryTagQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new category tag record
 * @summary Create a category tag
 */
export const postApiV10CategoryTag = (
    categoryTagMutate: BodyType<CategoryTagMutate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10CategoryTag200>(
      {url: `/api/v1.0/categoryTag`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryTagMutate, signal
    },
      options);
    }
  


export const getPostApiV10CategoryTagMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10CategoryTag>>, TError,{data: BodyType<CategoryTagMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10CategoryTag>>, TError,{data: BodyType<CategoryTagMutate>}, TContext> => {

const mutationKey = ['postApiV10CategoryTag'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10CategoryTag>>, {data: BodyType<CategoryTagMutate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10CategoryTag(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10CategoryTagMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10CategoryTag>>>
    export type PostApiV10CategoryTagMutationBody = BodyType<CategoryTagMutate>
    export type PostApiV10CategoryTagMutationError = ErrorType<unknown>

    /**
 * @summary Create a category tag
 */
export const usePostApiV10CategoryTag = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10CategoryTag>>, TError,{data: BodyType<CategoryTagMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10CategoryTag>>,
        TError,
        {data: BodyType<CategoryTagMutate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10CategoryTagMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    