/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10PostId200,
  GetApiV10PostId200,
  GetApiV10PostIdHistory200,
  GetApiV10PostParams,
  PostApiV10Post200,
  PostMutate,
  PutApiV10PostId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single post record by its ID
 * @summary Get post by ID
 */
export const getApiV10PostId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10PostId200>(
      {url: `/api/v1.0/post/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10PostIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/post/${id}`
    ] as const;
    }

export const getGetApiV10PostIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/post/${id}`
    ] as const;
    }

    
export const getGetApiV10PostIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PostId>>> = ({ signal }) => getApiV10PostId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PostId>>>
export type GetApiV10PostIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10PostIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get post by ID
 */

export function useGetApiV10PostIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get post by ID
 */
export const prefetchGetApiV10PostIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10PostId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10PostIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10PostId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PostId>>> = ({ signal }) => getApiV10PostId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PostId>>>
export type GetApiV10PostIdQueryError = ErrorType<void>


export function useGetApiV10PostId<TData = Awaited<ReturnType<typeof getApiV10PostId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostId<TData = Awaited<ReturnType<typeof getApiV10PostId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostId<TData = Awaited<ReturnType<typeof getApiV10PostId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get post by ID
 */

export function useGetApiV10PostId<TData = Awaited<ReturnType<typeof getApiV10PostId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get post by ID
 */
export const prefetchGetApiV10PostIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10PostId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single post record by its ID
 * @summary Update post by ID
 */
export const putApiV10PostId = (
    id: string,
    postMutate: BodyType<PostMutate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10PostId200>(
      {url: `/api/v1.0/post/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: postMutate
    },
      options);
    }
  


export const getPutApiV10PostIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10PostId>>, TError,{id: string;data: BodyType<PostMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10PostId>>, TError,{id: string;data: BodyType<PostMutate>}, TContext> => {

const mutationKey = ['putApiV10PostId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10PostId>>, {id: string;data: BodyType<PostMutate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10PostId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10PostIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10PostId>>>
    export type PutApiV10PostIdMutationBody = BodyType<PostMutate>
    export type PutApiV10PostIdMutationError = ErrorType<void>

    /**
 * @summary Update post by ID
 */
export const usePutApiV10PostId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10PostId>>, TError,{id: string;data: BodyType<PostMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10PostId>>,
        TError,
        {id: string;data: BodyType<PostMutate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10PostIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single post record by its ID
 * @summary Delete post by ID
 */
export const deleteApiV10PostId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10PostId200>(
      {url: `/api/v1.0/post/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10PostIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PostId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PostId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10PostId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10PostId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10PostId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10PostIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10PostId>>>
    
    export type DeleteApiV10PostIdMutationError = ErrorType<void>

    /**
 * @summary Delete post by ID
 */
export const useDeleteApiV10PostId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PostId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10PostId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10PostIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve the change history of a specific post
 * @summary Get post history
 */
export const getApiV10PostIdHistory = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10PostIdHistory200>(
      {url: `/api/v1.0/post/${id}/history`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10PostIdHistoryInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/post/${id}/history`
    ] as const;
    }

export const getGetApiV10PostIdHistoryQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/post/${id}/history`
    ] as const;
    }

    
export const getGetApiV10PostIdHistoryInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostIdHistory>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostIdHistoryInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PostIdHistory>>> = ({ signal }) => getApiV10PostIdHistory(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostIdHistoryInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PostIdHistory>>>
export type GetApiV10PostIdHistoryInfiniteQueryError = ErrorType<void>


export function useGetApiV10PostIdHistoryInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostIdHistory>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostIdHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostIdHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostIdHistoryInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostIdHistory>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostIdHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostIdHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostIdHistoryInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostIdHistory>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get post history
 */

export function useGetApiV10PostIdHistoryInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostIdHistory>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostIdHistoryInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get post history
 */
export const prefetchGetApiV10PostIdHistoryInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostIdHistoryInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10PostIdHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostIdHistoryQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PostIdHistory>>> = ({ signal }) => getApiV10PostIdHistory(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostIdHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PostIdHistory>>>
export type GetApiV10PostIdHistoryQueryError = ErrorType<void>


export function useGetApiV10PostIdHistory<TData = Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostIdHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostIdHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostIdHistory<TData = Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostIdHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostIdHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostIdHistory<TData = Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get post history
 */

export function useGetApiV10PostIdHistory<TData = Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostIdHistoryQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get post history
 */
export const prefetchGetApiV10PostIdHistoryQuery = async <TData = Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostIdHistory>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostIdHistoryQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Retrieve a list of post with pagination, filtering and sorting
 * @summary Get all post
 */
export const getApiV10Post = (
    params?: GetApiV10PostParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/post`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10PostInfiniteQueryKey = (params?: GetApiV10PostParams,) => {
    return [
    'infinite', `/api/v1.0/post`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10PostQueryKey = (params?: GetApiV10PostParams,) => {
    return [
    `/api/v1.0/post`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10PostInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Post>>>, TError = ErrorType<unknown>>(params?: GetApiV10PostParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Post>>> = ({ signal }) => getApiV10Post(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Post>>>
export type GetApiV10PostInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10PostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Post>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10PostParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Post>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Post>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Post>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Post>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Post>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Post>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all post
 */

export function useGetApiV10PostInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Post>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all post
 */
export const prefetchGetApiV10PostInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Post>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10PostParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10PostQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Post>>, TError = ErrorType<unknown>>(params?: GetApiV10PostParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Post>>> = ({ signal }) => getApiV10Post(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Post>>>
export type GetApiV10PostQueryError = ErrorType<unknown>


export function useGetApiV10Post<TData = Awaited<ReturnType<typeof getApiV10Post>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10PostParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Post>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Post>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Post<TData = Awaited<ReturnType<typeof getApiV10Post>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Post>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Post>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Post<TData = Awaited<ReturnType<typeof getApiV10Post>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all post
 */

export function useGetApiV10Post<TData = Awaited<ReturnType<typeof getApiV10Post>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all post
 */
export const prefetchGetApiV10PostQuery = async <TData = Awaited<ReturnType<typeof getApiV10Post>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10PostParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Post>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new post record
 * @summary Create a post
 */
export const postApiV10Post = (
    postMutate: BodyType<PostMutate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10Post200>(
      {url: `/api/v1.0/post`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postMutate, signal
    },
      options);
    }
  


export const getPostApiV10PostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Post>>, TError,{data: BodyType<PostMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Post>>, TError,{data: BodyType<PostMutate>}, TContext> => {

const mutationKey = ['postApiV10Post'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Post>>, {data: BodyType<PostMutate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Post(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10PostMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Post>>>
    export type PostApiV10PostMutationBody = BodyType<PostMutate>
    export type PostApiV10PostMutationError = ErrorType<unknown>

    /**
 * @summary Create a post
 */
export const usePostApiV10Post = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Post>>, TError,{data: BodyType<PostMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Post>>,
        TError,
        {data: BodyType<PostMutate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10PostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    