/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10PostTagPostIdParams,
  GetApiV10PostTagParams,
  GetApiV10PostTagPostIdParams,
  PostApiV10PostTag200,
  PostApiV10PostTagBody,
  PostApiV10PostTagPostIdBulk200,
  PostApiV10PostTagPostIdBulkBody,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve all tags for a specific post
 * @summary Get post tags by post ID
 */
export const getApiV10PostTagPostId = (
    postId: string,
    params?: GetApiV10PostTagPostIdParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/postTag/${postId}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10PostTagPostIdInfiniteQueryKey = (postId?: string,
    params?: GetApiV10PostTagPostIdParams,) => {
    return [
    'infinite', `/api/v1.0/postTag/${postId}`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10PostTagPostIdQueryKey = (postId?: string,
    params?: GetApiV10PostTagPostIdParams,) => {
    return [
    `/api/v1.0/postTag/${postId}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10PostTagPostIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTagPostId>>>, TError = ErrorType<unknown>>(postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostTagPostIdInfiniteQueryKey(postId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PostTagPostId>>> = ({ signal }) => getApiV10PostTagPostId(postId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(postId),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostTagPostIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PostTagPostId>>>
export type GetApiV10PostTagPostIdInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10PostTagPostIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTagPostId>>>, TError = ErrorType<unknown>>(
 postId: string,
    params: undefined |  GetApiV10PostTagPostIdParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostTagPostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostTagPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostTagPostIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTagPostId>>>, TError = ErrorType<unknown>>(
 postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostTagPostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostTagPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostTagPostIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTagPostId>>>, TError = ErrorType<unknown>>(
 postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get post tags by post ID
 */

export function useGetApiV10PostTagPostIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTagPostId>>>, TError = ErrorType<unknown>>(
 postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostTagPostIdInfiniteQueryOptions(postId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get post tags by post ID
 */
export const prefetchGetApiV10PostTagPostIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostTagPostIdInfiniteQueryOptions(postId,params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10PostTagPostIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError = ErrorType<unknown>>(postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostTagPostIdQueryKey(postId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PostTagPostId>>> = ({ signal }) => getApiV10PostTagPostId(postId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(postId),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostTagPostIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PostTagPostId>>>
export type GetApiV10PostTagPostIdQueryError = ErrorType<unknown>


export function useGetApiV10PostTagPostId<TData = Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError = ErrorType<unknown>>(
 postId: string,
    params: undefined |  GetApiV10PostTagPostIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostTagPostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostTagPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostTagPostId<TData = Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError = ErrorType<unknown>>(
 postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostTagPostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostTagPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostTagPostId<TData = Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError = ErrorType<unknown>>(
 postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get post tags by post ID
 */

export function useGetApiV10PostTagPostId<TData = Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError = ErrorType<unknown>>(
 postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostTagPostIdQueryOptions(postId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get post tags by post ID
 */
export const prefetchGetApiV10PostTagPostIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, postId: string,
    params?: GetApiV10PostTagPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTagPostId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostTagPostIdQueryOptions(postId,params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Delete a specific post-tag association
 * @summary Delete a post tag
 */
export const deleteApiV10PostTagPostId = (
    postId: string,
    params: DeleteApiV10PostTagPostIdParams,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/postTag/${postId}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteApiV10PostTagPostIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PostTagPostId>>, TError,{postId: string;params: DeleteApiV10PostTagPostIdParams}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PostTagPostId>>, TError,{postId: string;params: DeleteApiV10PostTagPostIdParams}, TContext> => {

const mutationKey = ['deleteApiV10PostTagPostId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10PostTagPostId>>, {postId: string;params: DeleteApiV10PostTagPostIdParams}> = (props) => {
          const {postId,params} = props ?? {};

          return  deleteApiV10PostTagPostId(postId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10PostTagPostIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10PostTagPostId>>>
    
    export type DeleteApiV10PostTagPostIdMutationError = ErrorType<unknown>

    /**
 * @summary Delete a post tag
 */
export const useDeleteApiV10PostTagPostId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PostTagPostId>>, TError,{postId: string;params: DeleteApiV10PostTagPostIdParams}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10PostTagPostId>>,
        TError,
        {postId: string;params: DeleteApiV10PostTagPostIdParams},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10PostTagPostIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Create multiple post-tag associations for a single post
 * @summary Bulk create post tags
 */
export const postApiV10PostTagPostIdBulk = (
    postId: string,
    postApiV10PostTagPostIdBulkBody: BodyType<PostApiV10PostTagPostIdBulkBody>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10PostTagPostIdBulk200>(
      {url: `/api/v1.0/postTag/${postId}/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV10PostTagPostIdBulkBody, signal
    },
      options);
    }
  


export const getPostApiV10PostTagPostIdBulkMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10PostTagPostIdBulk>>, TError,{postId: string;data: BodyType<PostApiV10PostTagPostIdBulkBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10PostTagPostIdBulk>>, TError,{postId: string;data: BodyType<PostApiV10PostTagPostIdBulkBody>}, TContext> => {

const mutationKey = ['postApiV10PostTagPostIdBulk'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10PostTagPostIdBulk>>, {postId: string;data: BodyType<PostApiV10PostTagPostIdBulkBody>}> = (props) => {
          const {postId,data} = props ?? {};

          return  postApiV10PostTagPostIdBulk(postId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10PostTagPostIdBulkMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10PostTagPostIdBulk>>>
    export type PostApiV10PostTagPostIdBulkMutationBody = BodyType<PostApiV10PostTagPostIdBulkBody>
    export type PostApiV10PostTagPostIdBulkMutationError = ErrorType<unknown>

    /**
 * @summary Bulk create post tags
 */
export const usePostApiV10PostTagPostIdBulk = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10PostTagPostIdBulk>>, TError,{postId: string;data: BodyType<PostApiV10PostTagPostIdBulkBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10PostTagPostIdBulk>>,
        TError,
        {postId: string;data: BodyType<PostApiV10PostTagPostIdBulkBody>},
        TContext
      > => {

      const mutationOptions = getPostApiV10PostTagPostIdBulkMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of post tags with pagination, filtering and sorting
 * @summary Get all post tags
 */
export const getApiV10PostTag = (
    params?: GetApiV10PostTagParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/postTag`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10PostTagInfiniteQueryKey = (params?: GetApiV10PostTagParams,) => {
    return [
    'infinite', `/api/v1.0/postTag`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10PostTagQueryKey = (params?: GetApiV10PostTagParams,) => {
    return [
    `/api/v1.0/postTag`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10PostTagInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTag>>>, TError = ErrorType<unknown>>(params?: GetApiV10PostTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostTagInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PostTag>>> = ({ signal }) => getApiV10PostTag(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostTagInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PostTag>>>
export type GetApiV10PostTagInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10PostTagInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTag>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10PostTagParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostTag>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostTagInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTag>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostTag>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostTagInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTag>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all post tags
 */

export function useGetApiV10PostTagInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PostTag>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostTagInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all post tags
 */
export const prefetchGetApiV10PostTagInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10PostTag>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10PostTagParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostTagInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10PostTagQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10PostTag>>, TError = ErrorType<unknown>>(params?: GetApiV10PostTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PostTagQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PostTag>>> = ({ signal }) => getApiV10PostTag(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PostTagQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PostTag>>>
export type GetApiV10PostTagQueryError = ErrorType<unknown>


export function useGetApiV10PostTag<TData = Awaited<ReturnType<typeof getApiV10PostTag>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10PostTagParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostTag>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostTag<TData = Awaited<ReturnType<typeof getApiV10PostTag>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PostTag>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PostTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PostTag<TData = Awaited<ReturnType<typeof getApiV10PostTag>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all post tags
 */

export function useGetApiV10PostTag<TData = Awaited<ReturnType<typeof getApiV10PostTag>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PostTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PostTagQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all post tags
 */
export const prefetchGetApiV10PostTagQuery = async <TData = Awaited<ReturnType<typeof getApiV10PostTag>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10PostTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PostTag>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PostTagQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new post tag record
 * @summary Create a post tag
 */
export const postApiV10PostTag = (
    postApiV10PostTagBody: BodyType<PostApiV10PostTagBody>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10PostTag200>(
      {url: `/api/v1.0/postTag`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV10PostTagBody, signal
    },
      options);
    }
  


export const getPostApiV10PostTagMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10PostTag>>, TError,{data: BodyType<PostApiV10PostTagBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10PostTag>>, TError,{data: BodyType<PostApiV10PostTagBody>}, TContext> => {

const mutationKey = ['postApiV10PostTag'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10PostTag>>, {data: BodyType<PostApiV10PostTagBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10PostTag(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10PostTagMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10PostTag>>>
    export type PostApiV10PostTagMutationBody = BodyType<PostApiV10PostTagBody>
    export type PostApiV10PostTagMutationError = ErrorType<unknown>

    /**
 * @summary Create a post tag
 */
export const usePostApiV10PostTag = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10PostTag>>, TError,{data: BodyType<PostApiV10PostTagBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10PostTag>>,
        TError,
        {data: BodyType<PostApiV10PostTagBody>},
        TContext
      > => {

      const mutationOptions = getPostApiV10PostTagMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    