/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10RolePermissionBulk200,
  DeleteApiV10RolePermissionRoleRoleId200,
  GetApiV10RolePermissionParams,
  PostApiV10RolePermissionRoleRoleIdBulk200,
  ResponseGetAllData,
  RolePermissionBulkCreateByRole,
  RolePermissionBulkDelete
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Delete multiple role permission records by their IDs
 * @summary Bulk delete role permissions
 */
export const deleteApiV10RolePermissionBulk = (
    rolePermissionBulkDelete: BodyType<RolePermissionBulkDelete>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10RolePermissionBulk200>(
      {url: `/api/v1.0/rolePermission/bulk`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: rolePermissionBulkDelete
    },
      options);
    }
  


export const getDeleteApiV10RolePermissionBulkMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10RolePermissionBulk>>, TError,{data: BodyType<RolePermissionBulkDelete>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10RolePermissionBulk>>, TError,{data: BodyType<RolePermissionBulkDelete>}, TContext> => {

const mutationKey = ['deleteApiV10RolePermissionBulk'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10RolePermissionBulk>>, {data: BodyType<RolePermissionBulkDelete>}> = (props) => {
          const {data} = props ?? {};

          return  deleteApiV10RolePermissionBulk(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10RolePermissionBulkMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10RolePermissionBulk>>>
    export type DeleteApiV10RolePermissionBulkMutationBody = BodyType<RolePermissionBulkDelete>
    export type DeleteApiV10RolePermissionBulkMutationError = ErrorType<void>

    /**
 * @summary Bulk delete role permissions
 */
export const useDeleteApiV10RolePermissionBulk = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10RolePermissionBulk>>, TError,{data: BodyType<RolePermissionBulkDelete>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10RolePermissionBulk>>,
        TError,
        {data: BodyType<RolePermissionBulkDelete>},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10RolePermissionBulkMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of role permissions with pagination, filtering and sorting
 * @summary Get all role permissions
 */
export const getApiV10RolePermission = (
    params?: GetApiV10RolePermissionParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/rolePermission`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10RolePermissionInfiniteQueryKey = (params?: GetApiV10RolePermissionParams,) => {
    return [
    'infinite', `/api/v1.0/rolePermission`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10RolePermissionQueryKey = (params?: GetApiV10RolePermissionParams,) => {
    return [
    `/api/v1.0/rolePermission`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10RolePermissionInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RolePermission>>>, TError = ErrorType<unknown>>(params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10RolePermissionInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10RolePermission>>> = ({ signal }) => getApiV10RolePermission(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10RolePermissionInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10RolePermission>>>
export type GetApiV10RolePermissionInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10RolePermissionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RolePermission>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10RolePermissionParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RolePermission>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RolePermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RolePermissionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RolePermission>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RolePermission>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RolePermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RolePermissionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RolePermission>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all role permissions
 */

export function useGetApiV10RolePermissionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RolePermission>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10RolePermissionInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all role permissions
 */
export const prefetchGetApiV10RolePermissionInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10RolePermission>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10RolePermissionInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10RolePermissionQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10RolePermission>>, TError = ErrorType<unknown>>(params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10RolePermissionQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10RolePermission>>> = ({ signal }) => getApiV10RolePermission(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10RolePermissionQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10RolePermission>>>
export type GetApiV10RolePermissionQueryError = ErrorType<unknown>


export function useGetApiV10RolePermission<TData = Awaited<ReturnType<typeof getApiV10RolePermission>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10RolePermissionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RolePermission>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RolePermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RolePermission<TData = Awaited<ReturnType<typeof getApiV10RolePermission>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RolePermission>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RolePermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RolePermission<TData = Awaited<ReturnType<typeof getApiV10RolePermission>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all role permissions
 */

export function useGetApiV10RolePermission<TData = Awaited<ReturnType<typeof getApiV10RolePermission>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10RolePermissionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all role permissions
 */
export const prefetchGetApiV10RolePermissionQuery = async <TData = Awaited<ReturnType<typeof getApiV10RolePermission>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10RolePermissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RolePermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10RolePermissionQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Delete all role permission records associated with a specific role ID
 * @summary Delete all permissions of a role
 */
export const deleteApiV10RolePermissionRoleRoleId = (
    roleId: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10RolePermissionRoleRoleId200>(
      {url: `/api/v1.0/rolePermission/role/${roleId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10RolePermissionRoleRoleIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10RolePermissionRoleRoleId>>, TError,{roleId: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10RolePermissionRoleRoleId>>, TError,{roleId: string}, TContext> => {

const mutationKey = ['deleteApiV10RolePermissionRoleRoleId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10RolePermissionRoleRoleId>>, {roleId: string}> = (props) => {
          const {roleId} = props ?? {};

          return  deleteApiV10RolePermissionRoleRoleId(roleId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10RolePermissionRoleRoleIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10RolePermissionRoleRoleId>>>
    
    export type DeleteApiV10RolePermissionRoleRoleIdMutationError = ErrorType<void>

    /**
 * @summary Delete all permissions of a role
 */
export const useDeleteApiV10RolePermissionRoleRoleId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10RolePermissionRoleRoleId>>, TError,{roleId: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10RolePermissionRoleRoleId>>,
        TError,
        {roleId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10RolePermissionRoleRoleIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Assign multiple permissions to a specific role at once. Role ID is in the path, permission IDs are in the request body.
 * @summary Bulk create role permissions by role ID
 */
export const postApiV10RolePermissionRoleRoleIdBulk = (
    roleId: string,
    rolePermissionBulkCreateByRole: BodyType<RolePermissionBulkCreateByRole>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10RolePermissionRoleRoleIdBulk200>(
      {url: `/api/v1.0/rolePermission/role/${roleId}/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rolePermissionBulkCreateByRole, signal
    },
      options);
    }
  


export const getPostApiV10RolePermissionRoleRoleIdBulkMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10RolePermissionRoleRoleIdBulk>>, TError,{roleId: string;data: BodyType<RolePermissionBulkCreateByRole>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10RolePermissionRoleRoleIdBulk>>, TError,{roleId: string;data: BodyType<RolePermissionBulkCreateByRole>}, TContext> => {

const mutationKey = ['postApiV10RolePermissionRoleRoleIdBulk'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10RolePermissionRoleRoleIdBulk>>, {roleId: string;data: BodyType<RolePermissionBulkCreateByRole>}> = (props) => {
          const {roleId,data} = props ?? {};

          return  postApiV10RolePermissionRoleRoleIdBulk(roleId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10RolePermissionRoleRoleIdBulkMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10RolePermissionRoleRoleIdBulk>>>
    export type PostApiV10RolePermissionRoleRoleIdBulkMutationBody = BodyType<RolePermissionBulkCreateByRole>
    export type PostApiV10RolePermissionRoleRoleIdBulkMutationError = ErrorType<void>

    /**
 * @summary Bulk create role permissions by role ID
 */
export const usePostApiV10RolePermissionRoleRoleIdBulk = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10RolePermissionRoleRoleIdBulk>>, TError,{roleId: string;data: BodyType<RolePermissionBulkCreateByRole>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10RolePermissionRoleRoleIdBulk>>,
        TError,
        {roleId: string;data: BodyType<RolePermissionBulkCreateByRole>},
        TContext
      > => {

      const mutationOptions = getPostApiV10RolePermissionRoleRoleIdBulkMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    